// Generated by CoffeeScript 1.4.0
var accountTemplate;

accountTemplate = function(account, i18n) {
  var template, unreadCount;
  if (account.unreadCount > 0) {
    unreadCount = "<span class=\"unreadCount\">(" + account.unreadCount + ")</span>";
  } else {
    unreadCount = "";
  }
  return template = "<div id=\"content_" + account.id + "\" class=\"indicator i" + (account.id % 4) + " account\">\n   <div id=\"inbox_" + account.id + "\" class=\"vbox rounded\">\n       <div class=\"hbox padded inbox\">\n           <div class=\"hbox padded wide\">\n              <a class=\"toggleLink imageLink\" accountId=\"" + account.id + "\" href=\"#\" title=\"\"><img src=\"/assets/img/arrow_down.png\" /></a>\n              <a class=\"inboxLink\" accountId=\"" + account.id + "\" href=\"#\" title=\"" + (account.getInboxLink()) + "\">\n                " + (account.getInboxLink()) + "\n                " + unreadCount + "\n              </a>\n           </div>\n           <div class=\"hbox padded\" style=\"padding-right: 0\">\n               <a class=\"composeLink imageLink\" accountId=\"" + account.id + "\" href=\"#\" title=\"" + (i18n.get('composeLinkTitle')) + "\"><img src=\"/assets/img/compose.png\" /></a>\n               <a class=\"sendpageLink imageLink\" accountId=\"" + account.id + "\" href=\"#\" title=\"" + (i18n.get('sendPageLinkTitle')) + "\"><img src=\"/assets/img/send_page.png\" /></a>\n           </div>\n       </div>\n   </div>\n</div>";
};
