// Generated by CoffeeScript 1.4.0
var mailUrl, openInTab, rewriteMailtoToGMailUrl, rewriteMailtosOnPage;

mailUrl = "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=";

openInTab = false;

chrome.extension.sendMessage({
  command: "getURL"
}, function(response) {
  if ((response != null ? response.URL : void 0) != null) {
    mailUrl = response.URL + "?view=cm&fs=1&tf=1&to=";
    openInTab = response.openTab;
    setTimeout(rewriteMailtosOnPage, 500);
    return setTimeout(rewriteMailtosOnPage, 5000);
  }
});

rewriteMailtoToGMailUrl = function(inUrl) {
  var retUrl, subject;
  retUrl = inUrl;
  subject = retUrl.match(/subject=([^&]*)/i);
  if (subject != null) {
    subject = encodeURIComponent(unescape(subject[1]));
    retUrl = retUrl.replace(/subject=([^&]*)/i, "su=" + subject);
  }
  retUrl = retUrl.replace("?", "&");
  retUrl = retUrl.replace(/CC=/i, "cc=");
  retUrl = retUrl.replace(/BCC=/i, "bcc=");
  retUrl = retUrl.replace(/Body=/i, "body=");
  retUrl = retUrl.replace(/mailto:/i, mailUrl);
  return retUrl;
};

rewriteMailtosOnPage = function() {
  var gmail_url, item, mailto_url, node, nodes, result, xpath, _i, _len, _results;
  xpath = "//a[contains(" + "translate(@href," + "'ABCDEFGHIJKLMNOPQRSTUVWXYZ'," + "'abcdefghijklmnopqrstuvwxyz')," + "'mailto:')]";
  result = document.evaluate(xpath, document, null, XPathResult.UNORDERED_NODE_ITERATOR_TYPE, null);
  item = void 0;
  nodes = [];
  while (item = result.iterateNext()) {
    nodes.push(item);
  }
  _results = [];
  for (_i = 0, _len = nodes.length; _i < _len; _i++) {
    node = nodes[_i];
    mailto_url = node.getAttribute('href');
    gmail_url = rewriteMailtoToGMailUrl(mailto_url);
    node.setAttribute("title", "[GMCP] Compose a new mail to " + node.innerText);
    if (openInTab) {
      node.setAttribute("href", gmail_url);
      node.setAttribute("target", "_blank");
    } else {
      node.setAttribute("href", mailto_url);
      node.setAttribute("onclick", "window.open('" + gmail_url + "','Compose new message','width=640,height=480');return false");
    }
    _results.push(node.setAttribute("rel", "noreferrer"));
  }
  return _results;
};
