// Generated by CoffeeScript 1.4.0
var archiveMail, deleteMail, mailAccount, openInbox, openMail, readMail, spamMail, starMail;

mailAccount = void 0;

openMail = function() {
  window.close();
  return mailAccount.openNewestMail();
};

readMail = function() {
  window.close();
  return mailAccount.readNewestMail();
};

deleteMail = function() {
  window.close();
  return mailAccount.deleteNewestMail();
};

spamMail = function() {
  window.close();
  return mailAccount.spamNewestMail();
};

archiveMail = function() {
  window.close();
  return mailAccount.archiveNewestMail();
};

starMail = function() {
  return mailAccount.starNewestMail();
};

openInbox = function() {
  return mailAccount.openInbox();
};

$(document).ready(function() {
  var backgroundPage, datetime, fullDateTime, mail, mailHtml, mailURL, profilePhotos;
  backgroundPage = chrome.extension.getBackgroundPage();
  mailAccount = backgroundPage.accountWithNewestMail;
  mailAccount.id = backgroundPage.accounts.indexOf(mailAccount);
  mail = backgroundPage.accountWithNewestMail.getNewestMail();
  mailURL = backgroundPage.accountWithNewestMail.getURL();
  profilePhotos = backgroundPage.profilePhotos;
  fullDateTime = mail.issued.toLocaleString();
  datetime = formatDateTime(mail.issued, i18n.selected_lang.months);
  mailHtml = notifyTemplate(mailAccount, datetime, i18n, mail);
  $("body").append(mailHtml);
  $("body").hover((function() {
    return $(this).find(".hiddenSummaryActions").fadeIn("fast");
  }), function() {
    return $(this).find(".hiddenSummaryActions").fadeOut("fast");
  });
  $("body").find(".readLink").click(function() {
    return readMail();
  });
  $("body").find(".deleteLink").click(function() {
    return deleteMail();
  });
  $("body").find(".spamLink").click(function() {
    return spamMail();
  });
  $("body").find(".archiveLink").click(function() {
    return archiveMail();
  });
  $("body").find(".openLink").click(function() {
    return openMail();
  });
  $("body").find(".inboxLink").click(function() {
    return openInbox();
  });
  return $("body").find(".starLink").click(function() {
    $(this).css("opacity", "1");
    return starMail();
  });
});
