// Generated by CoffeeScript 1.4.0

document.addEventListener('DOMContentLoaded', function() {
  var el, _fn, _i, _len, _ref;
  _ref = document.getElementsByClassName('options-page');
  _fn = function(el) {
    return el.addEventListener('click', function(event) {
      return window.location.href = chrome.extension.getURL('views/options.html');
    });
  };
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    el = _ref[_i];
    _fn(el);
  }
  return document.getElementById('disable-ads').addEventListener('click', function(event) {
    AU.support.disable();
    return document.getElementById('ad-paragraph').innerHTML = 'Ads disabled, please consider donating!';
  });
});
