/* Copyright 2010 Google */ (function(){var c=!0,f=!1,g=parseInt,h=window,i=chrome,j="length",l="prototype",m="replace",o="save",r=q("(function(){({{$code}})();})();",{code:h.injection.toString()}),s=q("(function(){({{$code}})();})();",{code:h.injector.toString()});delete h.injector;delete h.injection;function t(a,b,d,e){b={pageLang:b,userLang:d,autoTrans:e};b.content=u(q(r,b));i.tabs.executeScript(a,{code:q(s,b)})}function v(a){var b={noEvents:c,content:u('window["_GOOG_TRANS_EXT_VER"] = "1";')};i.tabs.executeScript(a,{code:q(s,b)})}
function w(a){this.t=a;this.f=this.n=f}function x(a){a.f=c}function y(a,b,d){!a.n&&!a.f&&(a.n=c,a.u=b.url,a.l=d||"page_load",a.o="",z(a))}function z(a){0==navigator.platform.toLowerCase().indexOf("win")?i.tabs.detectLanguage(a.t,A(a.m,a)):a.m("und_non_win")}w[l].m=function(a){if(!this.f){if(!a||"und"==a||"und_non_win"==a||a.match("invalid"))a="auto";this.o=a;B(this)}};function B(a){i.i18n.getAcceptLanguages(A(a.r,a))}w[l].r=function(a){this.f||(a||(a=[]),this.e=a,C(this))};
function C(a){for(var b=G,d=!(!b.targetLang()&&!a.e[0]),e="auto"!=a.o,k=H(b.targetLang()||a.e[0]||"en"),p=H(a.o),D={},n=0;n<a.e[j];++n)D[H(a.e[n])]=c;n=f;if(d)if("page_load"==a.l&&b.autoTrans()){if(b.autoTransUrls().has(a.u)||e&&k!=p&&b.autoTransLangs().has(p))n=c}else"user_click"==a.l&&e&&k!=p&&(n=c);var E=c,F=I();if("page_load"==a.l&&!n&&(!b.autoDisplay()||!e||!d||k==p||D[p]||b.disabledLangs().has(p)||b.disabledUrls().has(a.u)||4001<=1E3*F[0]+F[1]))E=f;E&&t(a.t,p,k,n);a.n=f}
function J(){this.c={}}J[l].h=function(a,b,d){this.c[a]||(this.c[a]=new w(a));y(this.c[a],b,d);v(a)};J[l].detach=function(a){this.c[a]&&(x(this.c[a]),delete this.c[a])};function K(a,b){this.d=a;this.p=b}K[l].add=function(a){this.d[a]=c;this.p[o]()};K[l].remove=function(a){delete this.d[a];this.p[o]()};K[l].g=function(){var a=[],b;for(b in this.d)this.d[b]&&a.push(b);return a};K[l].has=function(a){return!!this.d[a]};function L(a,b){this.b=a;this.q=b}
L[l].add=function(a,b){this.b.push({type:a,pattern:b});this.q[o]()};L[l].remove=function(a){this.b.splice(a,1);this.q[o]()};L[l].i=function(){for(var a=[],b=0;b<this.b[j];++b)a[b]={type:this.b[b].type,pattern:this.b[b].pattern};return a};L[l].has=function(a){for(var b=0;b<this.b[j];++b){var d=this.b[b];if("re"==d.type)try{if(a.match(d.pattern))return c}catch(e){}else if(0<=a.indexOf(d.pattern))return c}return f};function M(){this.noSave=f;this.a={};N(this)}
function O(a,b,d){if(d){var e=new d(a.a[b],a);a[b]=function(){return e}}else{var k=a;a[b]=function(){return k.a[b]};a["set_"+b]=function(a){k.a[b]=a;k[o]()}}}
function N(a){var b=localStorage.getItem("user_options"),d={targetLang:"",autoDisplay:c,disabledLangs:{},disabledUrls:[],autoTrans:f,autoTransLangs:{},autoTransUrls:[]};if(b){a.a=JSON.parse(b);for(var e in d)e in a.a||(a.a[e]=d[e])}else a.a=d;a[o]();O(a,"targetLang");O(a,"autoDisplay");O(a,"autoTrans");O(a,"disabledLangs",K);O(a,"disabledUrls",L);O(a,"autoTransLangs",K);O(a,"autoTransUrls",L)}M[l].save=function(){this.noSave||localStorage.setItem("user_options",JSON.stringify(this.a));this.s&&this.s()};
M[l].j=function(){var a=new M;a.noSave=c;return a};M[l].assign=function(a){a.noSave=f;a[o]();a.noSave=c;N(this)};M[l].k=function(a){this.s=a};var P=new J,G=new M;function Q(){return P}function R(){return G}S(Q,"translate.getTranslateManager");T(J,"attach",J[l].h);T(J,"detach",J[l].detach);S(R,"translate.getUserOptions");T(M,"save",M[l][o]);T(M,"clone",M[l].j);T(M,"assign",M[l].assign);T(M,"setOnSave",M[l].k);T(L,"add",L[l].add);T(L,"remove",L[l].remove);T(L,"list",L[l].i);T(L,"has",L[l].has);
T(K,"add",K[l].add);T(K,"remove",K[l].remove);T(K,"list",K[l].g);T(K,"has",K[l].has);function S(a,b){for(var d=b.split("."),e=h,k=0;k<d[j]-1;++k)e=e[d[k]]||(e[d[k]]={});e[d[d[j]-1]]=a}function T(a,b,d){a[l][b]=d}function q(a,b){return a[m](/\{\{\$.*?\}\}/g,function(a){a=a.substr(3,a[j]-5);return String(b[a])||""})}function u(a){return a[m](/\\/g,"\\\\")[m](/'/g,"\\'")[m](/"/g,'\\"')[m](/\n/g,"\\n")}function H(a){a=String(a).toLowerCase()[m]("_","-");if("zh-cn"==a)return"zh-CN";if("zh-tw"==a)return"zh-TW";var b=a.indexOf("-"),a=0<=b?a.substring(0,b):a;return"zh"==a?"zh-CN":a}
function A(a,b,d){b||(b=h);if(2<arguments[j]){var e=Array[l].slice.call(arguments,2);return function(){var d=Array[l].slice.call(arguments);Array[l].unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}}function I(){var a=navigator.userAgent.match(/Chrome\/(\d+)\.(\d+).(\d+)?/),b=[0,0,0];a&&(b[0]=g(a[1],10)||0,b[1]=g(a[2],10)||0,b[2]=g(a[3],10)||0);return b};})();
