/* Copyright 2010 Google */ (function(){var c=parseInt,f=window,g=chrome,h="length",k="prototype",m="replace",p="save",s=r("(function(){({{$code}})();})();",{code:f.injection.toString()}),t=r("(function(){({{$code}})();})();",{code:f.injector.toString()});delete f.injector;delete f.injection;function u(a,b,d,e){b={pageLang:b,userLang:d,autoTrans:e};b.content=v(r(s,b));g.tabs.executeScript(a,{code:r(t,b)})}function w(a){var b={noEvents:!0,content:v('window["_GOOG_TRANS_EXT_VER"] = "1";')};g.tabs.executeScript(a,{code:r(t,b)})}
function x(a){this.t=a;this.f=this.n=!1}function y(a){a.f=!0}function z(a,b,d){a.n||a.f||(a.n=!0,a.u=b.url,a.l=d||"page_load",a.o="",A(a))}function A(a){0==navigator.platform.toLowerCase().indexOf("win")?g.tabs.detectLanguage(a.t,B(a.m,a)):a.m("und_non_win")}x[k].m=function(a){if(!this.f){if(!a||"und"==a||"und_non_win"==a||a.match("invalid"))a="auto";this.o=a;C(this)}};function C(a){g.i18n.getAcceptLanguages(B(a.r,a))}x[k].r=function(a){this.f||(a||(a=[]),this.e=a,D(this))};
function D(a){for(var b=H,d=!(!b.targetLang()&&!a.e[0]),e="auto"!=a.o,l=I(b.targetLang()||a.e[0]||"en"),q=I(a.o),E={},n=0;n<a.e[h];++n)E[I(a.e[n])]=!0;n=!1;if(d)if("page_load"==a.l&&b.autoTrans()){if(b.autoTransUrls().has(a.u)||e&&l!=q&&b.autoTransLangs().has(q))n=!0}else"user_click"==a.l&&e&&l!=q&&(n=!0);var F=!0,G=J();"page_load"!=a.l||n||b.autoDisplay()&&e&&d&&!(l==q||E[q]||b.disabledLangs().has(q)||b.disabledUrls().has(a.u)||4001<=1E3*G[0]+G[1])||(F=!1);F&&u(a.t,q,l,n);a.n=!1}
function K(){this.c={}}K[k].h=function(a,b,d){this.c[a]||(this.c[a]=new x(a));z(this.c[a],b,d);w(a)};K[k].detach=function(a){this.c[a]&&(y(this.c[a]),delete this.c[a])};function L(a,b){this.d=a;this.p=b}L[k].add=function(a){this.d[a]=!0;this.p[p]()};L[k].remove=function(a){delete this.d[a];this.p[p]()};L[k].g=function(){var a=[],b;for(b in this.d)this.d[b]&&a.push(b);return a};L[k].has=function(a){return!!this.d[a]};function M(a,b){this.b=a;this.q=b}
M[k].add=function(a,b){this.b.push({type:a,pattern:b});this.q[p]()};M[k].remove=function(a){this.b.splice(a,1);this.q[p]()};M[k].i=function(){for(var a=[],b=0;b<this.b[h];++b)a[b]={type:this.b[b].type,pattern:this.b[b].pattern};return a};M[k].has=function(a){for(var b=0;b<this.b[h];++b){var d=this.b[b];if("re"==d.type)try{if(a.match(d.pattern))return!0}catch(e){}else if(0<=a.indexOf(d.pattern))return!0}return!1};function N(){this.noSave=!1;this.a={};O(this)}
function P(a,b,d){if(d){var e=new d(a.a[b],a);a[b]=function(){return e}}else{var l=a;a[b]=function(){return l.a[b]};a["set_"+b]=function(a){l.a[b]=a;l[p]()}}}
function O(a){var b=localStorage.getItem("user_options"),d={targetLang:"",autoDisplay:!0,disabledLangs:{},disabledUrls:[],autoTrans:!1,autoTransLangs:{},autoTransUrls:[]};if(b){a.a=JSON.parse(b);for(var e in d)e in a.a||(a.a[e]=d[e])}else a.a=d;a[p]();P(a,"targetLang");P(a,"autoDisplay");P(a,"autoTrans");P(a,"disabledLangs",L);P(a,"disabledUrls",M);P(a,"autoTransLangs",L);P(a,"autoTransUrls",M)}N[k].save=function(){this.noSave||localStorage.setItem("user_options",JSON.stringify(this.a));this.s&&this.s()};
N[k].j=function(){var a=new N;a.noSave=!0;return a};N[k].assign=function(a){a.noSave=!1;a[p]();a.noSave=!0;O(this)};N[k].k=function(a){this.s=a};var Q=new K,H=new N;function R(){return Q}function S(){return H}T(R,"translate.getTranslateManager");U(K,"attach",K[k].h);U(K,"detach",K[k].detach);T(S,"translate.getUserOptions");U(N,"save",N[k][p]);U(N,"clone",N[k].j);U(N,"assign",N[k].assign);U(N,"setOnSave",N[k].k);U(M,"add",M[k].add);U(M,"remove",M[k].remove);U(M,"list",M[k].i);U(M,"has",M[k].has);
U(L,"add",L[k].add);U(L,"remove",L[k].remove);U(L,"list",L[k].g);U(L,"has",L[k].has);function T(a,b){for(var d=b.split("."),e=f,l=0;l<d[h]-1;++l)e=e[d[l]]||(e[d[l]]={});e[d[d[h]-1]]=a}function U(a,b,d){a[k][b]=d}function r(a,b){return a[m](/\{\{\$.*?\}\}/g,function(a){a=a.substr(3,a[h]-5);return String(b[a])||""})}function v(a){return a[m](/\\/g,"\\\\")[m](/'/g,"\\'")[m](/"/g,'\\"')[m](/\n/g,"\\n")}function I(a){a=String(a).toLowerCase()[m]("_","-");if("zh-cn"==a)return"zh-CN";if("zh-tw"==a)return"zh-TW";var b=a.indexOf("-");a=0<=b?a.substring(0,b):a;return"zh"==a?"zh-CN":a}
function B(a,b,d){b||(b=f);if(2<arguments[h]){var e=Array[k].slice.call(arguments,2);return function(){var d=Array[k].slice.call(arguments);Array[k].unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}}function J(){var a=navigator.userAgent.match(/Chrome\/(\d+)\.(\d+).(\d+)?/),b=[0,0,0];a&&(b[0]=c(a[1],10)||0,b[1]=c(a[2],10)||0,b[2]=c(a[3],10)||0);return b};})();
