/* Copyright 2010 Google */ (function(){var e=document;function f(a,c){return a.selectedIndex=c}function g(a,c){return a.display=c}var h="appendChild",k="length",l="prototype",m="selectedIndex",n="checked",p="value",q="style",r="options",s="createElement",t="firstChild",u="addEventListener";function w(){return"uid_"+(y=y+1||1)}var y;function z(a,c,b){var d=0,v;for(v in c){var x=e[s]("option");x.value=v;x.text=c[v];x.A=d++;a[h](x);v==b&&(x.selected=!0)}b||f(a,""==b?-1:0)}
function A(a,c,b){var d=a[r][b];a.removeChild(d);f(a,a[r][b]?b:b-1);a=!1;for(b=0;b<c[r][k];++b)if(d.A<c[r][b].A){c.insertBefore(d,c[r][b]);f(c,b);a=!0;break}a||(c[h](d),f(c,c[r][k]-1))}
function B(a,c,b,d){var v=C("langMapTemplate")[p];this.z=a;b.selectId=w();b.listId=w();b.addBtnId=w();b.removeBtnId=w();c.innerHTML=D(v,b);this.b=C(b.selectId);this.d=C(b.listId);this.l=C(b.addBtnId);this.m=C(b.removeBtnId);z(this.b,d);a=a.list();for(c=0;c<a[k];++c)for(b=a[c],d=0;d<this.b[r][k];++d)if(this.b[r][d][p]==b){A(this.b,this.d,d);break}this.b[t]&&f(this.b,0);E(this);this.l[u]("click",F(this.n,this));this.m[u]("click",F(this.o,this))}
function E(a){a.l.disabled=a.b[t]?"":"disabled";a.m.disabled=a.d[t]?"":"disabled"}B[l].n=function(){0>this.b[m]||(this.z.add(this.b[r][this.b[m]][p]),A(this.b,this.d,this.b[m]),E(this))};B[l].o=function(){0>this.d[m]||(this.z.remove(this.d[r][this.d[m]][p]),A(this.d,this.b,this.d[m]),E(this))};
function G(a,c,b){var d=C("urlListTemplate")[p];this.F=a;b.textId=w();b.reChkId=w();b.listId=w();b.addBtnId=w();b.removeBtnId=w();c.innerHTML=D(d,b);this.D=C(b.textId);this.B=C(b.reChkId);this.a=C(b.listId);this.G=C(b.addBtnId);this.p=C(b.removeBtnId);a=a.list();for(c=0;c<a[k];++c)b=a[c],d=e[s]("option"),d.text=("re"==b.type?"[RE]":"")+b.pattern,this.a[h](d);H(this);this.G[u]("click",F(this.q,this));this.p[u]("click",F(this.r,this))}function H(a){a.p.disabled=a.a[t]?"":"disabled"}
G[l].q=function(){this.F.add(this.B[n]?"re":"str",this.D[p]);var a=e[s]("option");a.text=(this.B[n]?"[RE]":"")+this.D[p];this.a[h](a);f(this.a,this.a[r][k]-1);H(this)};G[l].r=function(){if(!(0>this.a[m])){this.F.remove(this.a[m]);var a=this.a[m];this.a.removeChild(this.a[r][this.a[m]]);f(this.a,this.a[r][a]?a:a-1);H(this)}};var I=chrome.extension.getBackgroundPage();
function J(){this.c=I.translate.getUserOptions().clone();this.k=C("targetLangSel");this.e=C("autoDisplayChk");this.f=C("autoTransChk");this.h=C("autoDisplayMoreDiv");this.i=C("autoTransDiv");this.H=C("saveBtn");this.C=C("saveStatus")}J[l].g=function(){window._callback_=F(function(a){this.j=a.tl;K(this)},this);var a=e[s]("script");a.charset="UTF-8";a.src="https://translate.google.com/translate_a/l?client=tee&cb=_callback_";e.getElementsByTagName("head")[0][h](a)};
function K(a){z(a.k,a.j,a.c.targetLang()||"");a.k[u]("change",F(a.w,a));a.e.checked=a.c.autoDisplay();a.e[u]("change",F(a.s,a));a.f.checked=a.c.autoTrans();a.f[u]("change",F(a.t,a));a.I=new B(a.c.disabledLangs(),a.h[t],{title:"Excluded languages:"},a.j);a.J=new G(a.c.disabledUrls(),a.h.lastChild,{title:"Excluded URLs:"});a.K=new B(a.c.autoTransLangs(),a.i[t],{title:"Included languages:"},a.j);a.L=new G(a.c.autoTransUrls(),a.i.lastChild,{title:"Included URLs:"});a.H[u]("click",F(a.v,a));a.c.setOnSave(F(a.u,
a));L(a)}J[l].w=function(){this.c.set_targetLang(this.k[p])};J[l].s=function(){this.c.set_autoDisplay(this.e[n]);L(this)};J[l].t=function(){this.c.set_autoTrans(this.f[n]);L(this)};J[l].v=function(){I.translate.getUserOptions().assign(this.c);g(this.C[q],"")};J[l].u=function(){g(this.C[q],"none")};function L(a){a.e[n]||g(a.h[q],"none");a.f[n]||g(a.i[q],"none")}M();N();function C(a){return e.getElementById(a)}function M(){for(var a=J,c="OptionsControl",c=c.split("."),b=window,d=0;d<c[k]-1;++d)b=b[c[d]]||(b[c[d]]={});b[c[c[k]-1]]=a}function N(){var a=J,c="init",b=J[l].g;a[l][c]=b}function D(a,c){return a.replace(/\{\{\$.*?\}\}/g,function(a){a=a.substr(3,a[k]-5);return String(c[a])||""})}
function F(a,c,b){c||(c=window);if(2<arguments[k]){var d=Array[l].slice.call(arguments,2);return function(){var b=Array[l].slice.call(arguments);Array[l].unshift.apply(b,d);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}};})();
