var c,e=e||{};window.crx=e;e.S=function(a){console.log(Date.now()+": "+a)};e.Zc=function(){};e.Qa=function(a){e.S(a);throw Error(a);};e.bind=function(a,b,d){return a.call.apply(a.bind,arguments)};e.mf="mjmiijggifbmmlmdlkoekhpmlbofhnnn";e.xb=function(){this.qd=this.oa=null;this.pd()};e.xb.kf=1E4;e.xb.prototype.pd=function(){this.oa&&clearTimeout(this.oa);this.oa=null;this.qd=chrome.extension.connect(e.mf);this.qd.onDisconnect.addListener(e.bind(this.of,this))};e.xb.prototype.of=function(){this.oa&&clearTimeout(this.oa);this.oa=null;this.oa=setTimeout(e.bind(this.pd,this),e.xb.kf)};e.Hb=function(){this.K=[]};e.Hb.prototype.register=function(a,b){a.addListener(b);var d={$e:m(a,b)};this.K.push(d);return d};var m=function(a,b){return function(){a.removeListener(b)}};e.ListenerRegistry=e.Hb;e.i18n=e.i18n||{};e.i18n.wc=function(a){a=a||{};for(var b=document.querySelectorAll("[i18n-content]"),d,f=0;d=b[f];f++){var g=d.getAttribute("i18n-content");if(g)var h=chrome.i18n.getMessage.apply(null,[g].concat(a[g]||[]));h&&(d.innerHTML=h)}};e.i18n.If=function(a){e.i18n.wc(a);document.dir=chrome.i18n.getMessage("@@bidi_dir")};e.i18n=e.i18n;e.i18n.translateDom=e.i18n.wc;e.i18n.updateDom=e.i18n.If;e.notifications=e.notifications||{};e.notifications=e.notifications;e.a=e.a||{};e.pluspages=e.a;e.notifications.Lb=1E4;e.notifications.bb="SAPISID";e.notifications.cb=".google.com";e.notifications.Va=!1;e.notifications.Qf=["jgoepmocgafhnchmokaimcmlojpnlkhp","ljlimfijliceffddnmjecdgaihgocjfb","cpembckmhnjipbgbnfiocbgnkpjdokdd"];e.notifications.Pf=["dlppkpafhbajpcmmoheippocdidnckmm","oelnpeknnoppmfhhhidlahkkacchafkm","hmglfmpefabcafaimbpldpambdfomanl"];e.notifications.k={LOADING:0,Kb:1,Ua:2,ab:3};
e.notifications.Fg=function(){var a=chrome.extension.getBackgroundPage();a&&a.window.controller||e.Qa("Cannot access controller object for the background page.");return a.window.controller};window.crx=window.crx||{};window.crx.notifications=window.crx.notifications||{};window.crx.notifications.ENABLE_PLUSPAGES=e.notifications.Va;e.notifications.A=function(a){this.gd={};this.lc={};this.ya=this.Ha=!1;this.J=null;this.cd=a};e.notifications.A.$=null;e.notifications.A.create=function(a){e.notifications.A.$&&e.Qa("Trying to create a second Loader.");e.notifications.A.$=new e.notifications.A(!!a);return e.notifications.A.$};e.notifications.A.prototype.init=function(){this.load();var a=this;setTimeout(function(){a.Ha=!0;p(a)},0)};e.notifications.A.Ze="https://apis.google.com/js/plusone.js";e.notifications.A.Ye="https://apis.google.com/js/plusone.js?onload=onPlusOneLoaded_&googleapis=1";
function s(){e.notifications.A.$||e.Qa("Error: PlusOne API loaded but no loader created.");e.notifications.A.$.ya=!0;p(e.notifications.A.$)}var p=function(a){a.Ha&&a.ya&&a.ed(a.gd)};
e.notifications.A.prototype.load=function(){if(this.ya)p(this);else{this.J&&this.J.parentNode&&(this.J.parentNode.removeChild(this.J),this.J=null);this.J=document.createElement("script");this.J.type="text/javascript";this.J.async=!0;this.J.src=this.cd?e.notifications.A.Ze:e.notifications.A.Ye;this.J.onerror=e.bind(this.ed,this,this.lc);this.J.innerText="{lang: navigator.language}";this.cd&&this.J.addEventListener("load",s,!1);var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(this.J,
a)}};var u=function(a,b,d,f){a.Ha&&a.ya?d():(a.gd[b]=d,f?a.lc[b]=f:delete a.lc[b])};e.notifications.A.prototype.ed=function(a){for(var b in a){var d=a[b];d&&"function"==typeof d&&d();delete a[b]}};window.onPlusOneLoaded_=s;e.notifications.Wc="gpnext";e.notifications.De="https://plus.google.com/u/0/_/notifications/frame";e.notifications.Wf="https://www.google.com/accounts/ServiceLogin?service=oz";e.notifications.Iframe=function(a,b,d,f,g,h){this.G=null;this.Xe=f;this.We=g;this.fc=h;this.Xa=a;this.oc=document.getElementById(a);this.Ja=this.Na=null;this.X=b;this.Te=d};e.notifications.Iframe.Xc="iframe-style";e.notifications.Iframe.Ee=1E4;e.notifications.Iframe.prototype.init=function(){e.i18n.wc();this.oc=document.getElementById(this.Xa)};
var v=function(a,b,d){return{onOpen:function(b){return b.openInto(a.Xa)},onReady:function(f){if(b.onReady)b.onReady(f);d&&e.notifications.Iframe.vb(f,"onShowNotificationsOnly",{maxWidgetHeight:a.Te.qf,isExtension:!0})},onClose:function(a){if(b.onClose)b.onClose(a);a.remove()}}};e.notifications.Iframe.vb=function(a,b,d){a[b]&&"function"==typeof a[b]?a[b].apply(window,Array.prototype.slice.call(arguments,2)):e.Qa("Method "+b+" not defined on iframe.")};c=e.notifications.Iframe.prototype;
c.kc=function(a,b,d){d||(d={});w(this);this.Ja=setTimeout(e.bind(this.Fe,this),e.notifications.Iframe.Ee);if(this.X.Ha&&this.X.ya){iframes.setHandler(e.notifications.Iframe.Xc,v(this,a,b));a={setNotificationWidgetSize:e.bind(this.Je,this),setNotificationText:e.bind(this.Ie,this),postShareMessage:e.bind(e.Zc,this,"postShareMessage"),openSharebox:e.bind(e.Zc,this,"openSharebox"),onError:e.bind(this.Ge,this),hideNotificationWidget:window.close,onInfo:e.bind(this.He,this)};b=e.notifications.De+"#pid="+
e.notifications.Wc;for(var f in d)b+="&"+f+"="+d[f];this.G=iframes.open(b,{style:e.notifications.Iframe.Xc},{sourceid:e.notifications.Wc,origin:window.location.origin,hl:window.navigator.language},a,function(){})}else u(this.X,"iframe",e.bind(this.kc,this,a,b,d),e.bind(this.fc,this))};c.Fe=function(){this.Ja=null;e.S("Timeout during PlusOne API or iframe loading.");this.fc()};c.Je=function(a,b){x(this,a,b)};
c.Ie=function(a,b,d,f){w(this);d=parseInt(a,10);b||(b=9>=d?a:"9+");this.Xe(d,b,f&&f.hasUnread?!0:!1)};c.Ge=function(a,b){e.S("Error numer "+a+": "+b);this.fc()};c.He=function(a){w(this);3==a&&this.We()};var w=function(a){a.Ja&&(clearTimeout(a.Ja),a.Ja=null)};e.notifications.Iframe.prototype.load=function(a,b){this.kc(a,!1,b)};e.notifications.Iframe.prototype.open=function(a,b){this.kc(a,!0,b)};e.notifications.Iframe.prototype.close=function(){e.notifications.Iframe.vb(this.G,"onHide")};
var x=function(a,b,d){a.Na&&(clearTimeout(a.Na),a.Na=null);a.Na=setTimeout(function(){a.Na=null;a.oc.style.width=b;a.oc.style.height=d},100)};e.notifications.Iframe.prototype.vc=function(a){this.G&&this.G.onActive&&(a?e.notifications.Iframe.vb(this.G,"onActive"):e.notifications.Iframe.vb(this.G,"onIdle"))};e.a.Hd=function(){this.qf=580};e.a.k={Tb:0,sa:1};e.a.Za={Vf:0,Ec:1,CLOSED:2};e.a.ia={Jb:0,Ac:1,Bc:2};e.a.bb="SAPISID";e.a.cb=".google.com";e.a.Gc={permissions:[],origins:["http://*/*","https://www.googleapis.com/*","https://www.clients6.google.com/*"]};e.a.Vb="plus_follow_state";e.a.Ta="had_pre_plusfollow_build";e.a.Gb="plus_follow_offered";e.a.Mf="chrome-ext-brand-badge";e.a.Ud=["author","publisher","me"];e.a.Vd=/^https?:\/\/plus\.google\.com/;e.a.Jc=/\/\/[^\/]*\/[^\?]*([0-9]{21})/;e.a.Sd=/(Chrom(e|ium))\/([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/;
e.a.Od=[18,0,1025,162];e.a.Nd=[19,0,1084,35];e.a.lh=function(){var a=null;(a=e.a.eb(document.getElementsByTagName("link")))||(a=e.a.eb(document.getElementsByTagName("g:plus")));a||(a=e.a.eb(document.getElementsByClassName("g-plus")));a||(a=e.a.eb(document.getElementsByTagName("a")));return a};e.a.eb=function(a){for(var b=0;b<a.length;b++){var d=e.a.Zd(a[b]);if(d)return d}return null};
e.a.Yd=function(a){var b,d=[];"G:PLUS"==a.tagName?(b=e.a.$b(a.getAttribute("href")),d.push("publisher")):"DIV"==a.tagName?(b=e.a.$b(a.getAttribute("data-href")),d.push("publisher")):b=e.a.$b(a.href);if(b.valid)for(a.rel&&(d=d.concat(a.rel.split(" "))),b.Xb&&(d=d.concat(b.Xb)),a=0;a<d.length;a++)if(0<=e.a.Ud.indexOf(d[a]))return b.source};e.a.Zd=function(a){if(a=e.a.Yd(a))return e.a.Xd(a)};e.a.Xd=function(a){if(a=e.a.Jc.exec(a))return a[1]};
e.a.$b=function(a){var b={source:a,valid:!1,Xb:[]};if(!e.a.Vd.exec(a))return b;a=a.split("?",2);if(!e.a.Jc.exec(a[0]))return b;b.valid=!0;a[1]&&(a=("&"+a[1]).match(/&rel=([^&]*)/))&&(b.Xb=decodeURIComponent(a[1]).split(" "));return b};e.a.Hc=function(){var a=chrome.extension.getBackgroundPage();a&&a.window.tabManager||e.Qa("Cannot access tab manager object for the background page.");return a.window.tabManager};
e.a.vh=function(){window.localStorage.removeItem(e.a.Ta);window.localStorage.setItem(e.a.Gb,"true");chrome.extension.sendRequest({msg:"plusFollowPromoClick"})};e.a.Ef=function(){chrome.tabs.create({url:chrome.extension.getURL("followpromo.html")});chrome.extension.sendRequest({msg:"plusFollowPromoPageOpened"})};e.a.Kh=function(a){chrome.permissions.request(e.a.Gc,function(b){b?(e.a.Ub(e.a.k.sa),e.a.Hc().init(),chrome.extension.sendRequest({msg:"plusFollowActivated"})):e.a.Ub(e.a.k.Tb);a(b)})};
e.a.Ag=function(){e.a.Ub(e.a.k.Tb);e.a.Hc().cleanup();chrome.permissions.remove(e.a.Gc,function(){})};e.a.Dd=function(){return e.a.Wd()&&e.notifications.Va};e.a.xd=function(){return window.localStorage.getItem(e.a.Vb)};e.a.Ub=function(a){window.localStorage.setItem(e.a.Vb,a)};e.a.Pd=function(){var a=e.a.Sd.exec(window.navigator.userAgent);if(a&&3<a.length)return a[3];e.S("Chrome version extraction failed");return""};e.a.Wb=function(a,b){for(var d=0;d<a.length;d++){if(a[d]>b[d])return 1;if(a[d]<b[d])return-1}return 0};
e.a.Wd=function(){var a=e.a.Pd().split("."),b=e.a.Od,d=e.a.Nd;if(4>a.length)return e.S("Chrome version unknown, disabling +Follow"),!1;for(var f=[],g=0;g<a.length;g++)f.push(parseInt(a[g],10));return 0<=e.a.Wb(a,b)&&0>=e.a.Wb(a,d)?!1:!0};window.crx=window.crx||{};window.crx.pluspages=window.crx.pluspages||{};window.crx.pluspages.AUTO_UPDATE=e.a.Ta;window.crx.pluspages.onPopupPromoClicked=e.a.Ef;e.nb=function(){return window.localStorage};var y=y||{};y.global=this;y.xc=function(a,b,d){a=a.split(".");d=d||y.global;a[0]in d||!d.execScript||d.execScript("var "+a[0]);for(var f;a.length&&(f=a.shift());)a.length||void 0===b?d=d[f]?d[f]:d[f]={}:d[f]=b};y.zg=function(a,b){y.xc(a,b)};y.wb=!0;y.Tf="en";y.wd=!0;y.nh=function(a){y.xc(a)};y.uh=function(a){if(!y.wb)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
y.Kg=function(a){a=a.split(".");for(var b=y.global,d;d=a.shift();)if(y.Df(b[d]))b=b[d];else return null;return b};y.Pg=function(a,b){var d=b||y.global,f;for(f in a)d[f]=a[f]};y.ag=function(a,b,d){if(y.nd){var f;a=a.replace(/\\/g,"/");for(var g=y.Aa,h=0;f=b[h];h++)g.Oa[f]=a,a in g.uc||(g.uc[a]={}),g.uc[a][f]=!0;for(f=0;b=d[f];f++)a in g.Pa||(g.Pa[a]={}),g.Pa[a][b]=!0}};y.Nh=!1;y.Of=!0;y.sh=function(){};y.sb="";y.hh=function(){};y.Rg=function(a){return a};
y.$f=function(){throw Error("unimplemented abstract method");};y.bg=function(a){a.Kf=function(){if(a.$)return a.$;y.wb&&(y.sd[y.sd.length]=a);return a.$=new a}};y.sd=[];y.nd=!1;
y.nd&&(y.af={},y.Aa={uc:{},Oa:{},Pa:{},kd:{},tb:{}},y.ud=function(){var a=y.global.document;return"undefined"!=typeof a&&"write"in a},y.Bf=function(){if(y.global.uf)y.sb=y.global.uf;else if(y.ud())for(var a=y.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var d=a[b].src,f=d.lastIndexOf("?"),f=-1==f?d.length:f;if("base.js"==d.substr(f-7,7)){y.sb=d.substr(0,f-7);break}}},y.jd=function(a){var b=y.global.Lf||y.pf;!y.Aa.tb[a]&&b(a)&&(y.Aa.tb[a]=!0)},y.pf=function(a){if(y.ud()){var b=
y.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+a+'">\x3c/script>');return!0}return!1},y.Ph=function(){function a(g){if(!(g in f.tb)){if(!(g in f.kd)&&(f.kd[g]=!0,g in f.Pa))for(var k in f.Pa[g])if(!y.Jf(k))if(k in f.Oa)a(f.Oa[k]);else throw Error("Undefined nameToPath for "+k);g in d||(d[g]=!0,b.push(g))}}var b=[],d={},f=y.Aa,g;for(g in y.af)f.tb[g]||a(g);for(g=
0;g<b.length;g++)if(b[g])y.jd(y.sb+b[g]);else throw Error("Undefined script input");},y.Lg=function(a){return a in y.Aa.Oa?y.Aa.Oa[a]:null},y.Bf(),y.global.Nf||y.jd(y.sb+"deps.js"));
y.U=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};y.Pc=function(a){return void 0!==a};y.Zg=function(a){return null===a};y.Df=function(a){return null!=a};y.isArray=function(a){return"array"==y.U(a)};y.kb=function(a){var b=y.U(a);return"array"==b||"object"==b&&"number"==typeof a.length};y.Wg=function(a){return y.jc(a)&&"function"==typeof a.getFullYear};y.B=function(a){return"string"==typeof a};y.Oe=function(a){return"boolean"==typeof a};y.Qe=function(a){return"number"==typeof a};
y.Pe=function(a){return"function"==y.U(a)};y.jc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};y.qb=function(a){return a[y.zb]||(a[y.zb]=++y.vf)};y.Ff=function(a){"removeAttribute"in a&&a.removeAttribute(y.zb);try{delete a[y.zb]}catch(b){}};y.zb="closure_uid_"+(1E9*Math.random()>>>0);y.vf=0;y.Hg=y.qb;y.qh=y.Ff;y.nf=function(a){var b=y.U(a);if("object"==b||"array"==b){if(a.td)return a.td();var b="array"==b?[]:{},d;for(d in a)b[d]=y.nf(a[d]);return b}return a};
y.yf=function(a,b,d){return a.call.apply(a.bind,arguments)};y.xf=function(a,b,d){if(!a)throw Error();if(2<arguments.length){var f=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,f);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}};y.bind=function(a,b,d){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?y.bind=y.yf:y.bind=y.xf;return y.bind.apply(null,arguments)};
y.ga=function(a,b){var d=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,d);return a.apply(this,b)}};y.zd=function(a,b){for(var d in b)a[d]=b[d]};y.now=y.wd&&Date.now||function(){return+new Date};
y.Og=function(a){if(y.global.execScript)y.global.execScript(a,"JavaScript");else if(y.global.eval)if(null==y.Ab&&(y.global.eval("var _et_ = 1;"),"undefined"!=typeof y.global._et_?(delete y.global._et_,y.Ab=!0):y.Ab=!1),y.Ab)y.global.eval(a);else{var b=y.global.document,d=b.createElement("script");d.type="text/javascript";d.defer=!1;d.appendChild(b.createTextNode(a));b.body.appendChild(d);b.body.removeChild(d)}else throw Error("goog.globalEval not available");};y.Ab=null;
y.Gg=function(a,b){var d=function(a){return y.vd[a]||a},f=function(a){a=a.split("-");for(var b=[],f=0;f<a.length;f++)b.push(d(a[f]));return b.join("-")},f=y.vd?"BY_WHOLE"==y.wf?d:f:function(a){return a};return b?a+"-"+f(b):f(a)};y.th=function(a,b){y.vd=a;y.wf=b};y.Ig=function(a,b){var d=b||{},f;for(f in d){var g=(""+d[f]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+f+"\\}","gi"),g)}return a};y.Jg=function(a){return a};y.Ra=function(a,b){y.xc(a,b,void 0)};y.qa=function(a,b,d){a[b]=d};
y.F=function(a,b){function d(){}d.prototype=b.prototype;a.Ma=b.prototype;a.prototype=new d;a.prototype.constructor=a};
y.jg=function(a,b,d){var f=arguments.callee.caller;if(y.wb&&!f)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(f.Ma)return f.Ma.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var g=Array.prototype.slice.call(arguments,2),h=!1,k=a.constructor;k;k=k.Ma&&k.Ma.constructor)if(k.prototype[b]===f)h=!0;else if(h)return k.prototype[b].apply(a,g);if(a[b]===f)return a.constructor.prototype[b].apply(a,
g);throw Error("goog.base called from a method of one name to a method of a different name");};y.scope=function(a){a.call(y.global)};y.zf=!0;
y.zf&&(Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var d=Array.prototype.slice.call(arguments,1);d.unshift(this,a);return y.bind.apply(null,d)}return y.bind(this,a)},Function.prototype.ga=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return y.bind.apply(null,b)},Function.prototype.F=function(a){y.F(this,a)},Function.prototype.zd=function(a){y.zd(this.prototype,a)});y.debug={};y.debug.Ia=function(a){Error.captureStackTrace?Error.captureStackTrace(this,y.debug.Ia):this.stack=Error().stack||"";a&&(this.message=String(a))};y.F(y.debug.Ia,Error);y.debug.Ia.prototype.name="CustomError";y.b={};y.b.Zf={Uf:"\u00a0"};y.b.Ah=function(a,b){return 0==a.lastIndexOf(b,0)};y.b.Bg=function(a,b){var d=a.length-b.length;return 0<=d&&a.indexOf(b,d)==d};y.b.sg=function(a,b){return 0==y.b.Oc(b,a.substr(0,b.length))};y.b.qg=function(a,b){return 0==y.b.Oc(b,a.substr(a.length-b.length,b.length))};y.b.rg=function(a,b){return a.toLowerCase()==b.toLowerCase()};
y.b.he=function(a,b){for(var d=a.split("%s"),f="",g=Array.prototype.slice.call(arguments,1);g.length&&1<d.length;)f+=d.shift()+g.shift();return f+d.join("%s")};y.b.vg=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};y.b.dc=function(a){return/^[\s\xa0]*$/.test(a)};y.b.Xg=function(a){return y.b.dc(y.b.ie(a))};y.b.Vg=function(a){return!/[^\t\n\r ]/.test(a)};y.b.Tg=function(a){return!/[^a-zA-Z]/.test(a)};y.b.$g=function(a){return!/[^0-9]/.test(a)};y.b.Ug=function(a){return!/[^a-zA-Z0-9]/.test(a)};
y.b.bh=function(a){return" "==a};y.b.dh=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};y.b.Bh=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};y.b.pg=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};y.b.gh=function(a){return a.replace(/\xa0|\s/g," ")};y.b.fh=function(a){return a.replace(/\xa0|[ \t]+/g," ")};y.b.ug=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};y.b.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
y.b.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};y.b.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};y.b.Oc=function(a,b){var d=String(a).toLowerCase(),f=String(b).toLowerCase();return d<f?-1:d==f?0:1};y.b.Qc=/(\.\d+)|(\d+)|(\D+)/g;
y.b.ih=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var d=a.toLowerCase().match(y.b.Qc),f=b.toLowerCase().match(y.b.Qc),g=Math.min(d.length,f.length),h=0;h<g;h++){var k=d[h],l=f[h];if(k!=l)return d=parseInt(k,10),!isNaN(d)&&(f=parseInt(l,10),!isNaN(f)&&d-f)?d-f:k<l?-1:1}return d.length!=f.length?d.length-f.length:a<b?-1:1};y.b.Mh=function(a){return encodeURIComponent(String(a))};y.b.Lh=function(a){return decodeURIComponent(a.replace(/\+/g," "))};
y.b.oe=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};y.b.Mc=function(a){if(!y.b.ce.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(y.b.de,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(y.b.fe,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(y.b.ee,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(y.b.ge,"&quot;"));return a};y.b.de=/&/g;y.b.fe=/</g;y.b.ee=/>/g;y.b.ge=/\"/g;y.b.ce=/[&<>\"]/;y.b.Nc=function(a){return y.b.contains(a,"&")?"document"in y.global?y.b.ke(a):y.b.le(a):a};
y.b.ke=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},d=document.createElement("div");return a.replace(y.b.ne,function(a,g){var h=b[a];if(h)return h;if("#"==g.charAt(0)){var k=Number("0"+g.substr(1));isNaN(k)||(h=String.fromCharCode(k))}h||(d.innerHTML=a+" ",h=d.firstChild.nodeValue.slice(0,-1));return b[a]=h})};
y.b.le=function(a){return a.replace(/&([^;]+);/g,function(a,d){switch(d){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==d.charAt(0)){var f=Number("0"+d.substr(1));if(!isNaN(f))return String.fromCharCode(f)}return a}})};y.b.ne=/&([^;\s<&]+);?/g;y.b.Oh=function(a,b){return y.b.oe(a.replace(/  /g," &#160;"),b)};
y.b.Ch=function(a,b){for(var d=b.length,f=0;f<d;f++){var g=1==d?b:b.charAt(f);if(a.charAt(0)==g&&a.charAt(a.length-1)==g)return a.substring(1,a.length-1)}return a};y.b.truncate=function(a,b,d){d&&(a=y.b.Nc(a));a.length>b&&(a=a.substring(0,b-3)+"...");d&&(a=y.b.Mc(a));return a};
y.b.Jh=function(a,b,d,f){d&&(a=y.b.Nc(a));if(f&&a.length>b)f>b&&(f=b),a=a.substring(0,b-f)+"..."+a.substring(a.length-f);else if(a.length>b){f=Math.floor(b/2);var g=a.length-f;a=a.substring(0,f+b%2)+"..."+a.substring(g)}d&&(a=y.b.Mc(a));return a};y.b.cc={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};y.b.jb={"'":"\\'"};
y.b.quote=function(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],d=0;d<a.length;d++){var f=a.charAt(d),g=f.charCodeAt(0);b[d+1]=y.b.cc[f]||(31<g&&127>g?f:y.b.Lc(f))}b.push('"');return b.join("")};y.b.Cg=function(a){for(var b=[],d=0;d<a.length;d++)b[d]=y.b.Lc(a.charAt(d));return b.join("")};
y.b.Lc=function(a){if(a in y.b.jb)return y.b.jb[a];if(a in y.b.cc)return y.b.jb[a]=y.b.cc[a];var b=a,d=a.charCodeAt(0);if(31<d&&127>d)b=a;else{if(256>d){if(b="\\x",16>d||256<d)b+="0"}else b="\\u",4096>d&&(b+="0");b+=d.toString(16).toUpperCase()}return y.b.jb[a]=b};y.b.Eh=function(a){for(var b={},d=0;d<a.length;d++)b[a.charAt(d)]=!0;return b};y.b.contains=function(a,b){return-1!=a.indexOf(b)};y.b.xg=function(a,b){return a&&b?a.split(b).length-1:0};
y.b.lb=function(a,b,d){var f=a;0<=b&&(b<a.length&&0<d)&&(f=a.substr(0,b)+a.substr(b+d,a.length-b-d));return f};y.b.remove=function(a,b){var d=RegExp(y.b.ac(b),"");return a.replace(d,"")};y.b.removeAll=function(a,b){var d=RegExp(y.b.ac(b),"g");return a.replace(d,"")};y.b.ac=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};y.b.repeat=function(a,b){return Array(b+1).join(a)};
y.b.jh=function(a,b,d){a=y.Pc(d)?a.toFixed(d):String(a);d=a.indexOf(".");-1==d&&(d=a.length);return y.b.repeat("0",Math.max(0,b-d))+a};y.b.ie=function(a){return null==a?"":String(a)};y.b.og=function(a){return Array.prototype.join.call(arguments,"")};y.b.Mg=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^y.now()).toString(36)};
y.b.Wb=function(a,b){for(var d=0,f=y.b.trim(String(a)).split("."),g=y.b.trim(String(b)).split("."),h=Math.max(f.length,g.length),k=0;0==d&&k<h;k++){var l=f[k]||"",n=g[k]||"",q=RegExp("(\\d*)(\\D*)","g"),F=RegExp("(\\d*)(\\D*)","g");do{var t=q.exec(l)||["","",""],r=F.exec(n)||["","",""];if(0==t[0].length&&0==r[0].length)break;d=y.b.ec(0==t[1].length?0:parseInt(t[1],10),0==r[1].length?0:parseInt(r[1],10))||y.b.ec(0==t[2].length,0==r[2].length)||y.b.ec(t[2],r[2])}while(0==d)}return d};
y.b.ec=function(a,b){return a<b?-1:a>b?1:0};y.b.me=4294967296;y.b.Qg=function(a){for(var b=0,d=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=y.b.me;return b};y.b.pe=2147483648*Math.random()|0;y.b.yg=function(){return"goog_"+y.b.pe++};y.b.Fh=function(a){var b=Number(a);return 0==b&&y.b.dc(a)?NaN:b};y.b.Yg=function(a){return/^[a-z]+([A-Z][a-z]*)*$/.test(a)};y.b.eh=function(a){return/^([A-Z][a-z]*)+$/.test(a)};y.b.Dh=function(a){return String(a).replace(/\-([a-z])/g,function(a,d){return d.toUpperCase()})};
y.b.Hh=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};y.b.Ih=function(a,b){var d=y.B(b)?y.b.ac(b):"\\s";return a.replace(RegExp("(^"+(d?"|["+d+"]+":"")+")([a-z])","g"),function(a,b,d){return b+d.toUpperCase()})};y.b.kh=function(a){isFinite(a)&&(a=String(a));return y.B(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};y.b.yh=function(a,b,d){a=a.split(b);for(var f=[];0<d&&a.length;)f.push(a.shift()),d--;a.length&&f.push(a.join(b));return f};y.g={};y.g.Z=y.wb;y.g.rb=function(a,b){b.unshift(a);y.debug.Ia.call(this,y.b.he.apply(null,b));b.shift()};y.F(y.g.rb,y.debug.Ia);y.g.rb.prototype.name="AssertionError";y.g.ca=function(a,b,d,f){var g="Assertion failed";if(d)var g=g+(": "+d),h=f;else a&&(g+=": "+a,h=b);throw new y.g.rb(""+g,h||[]);};y.g.assert=function(a,b,d){y.g.Z&&!a&&y.g.ca("",null,b,Array.prototype.slice.call(arguments,2));return a};
y.g.Dg=function(a,b){if(y.g.Z)throw new y.g.rb("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};y.g.gg=function(a,b,d){y.g.Z&&!y.Qe(a)&&y.g.ca("Expected number but got %s: %s.",[y.U(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.g.ig=function(a,b,d){y.g.Z&&!y.B(a)&&y.g.ca("Expected string but got %s: %s.",[y.U(a),a],b,Array.prototype.slice.call(arguments,2));return a};
y.g.eg=function(a,b,d){y.g.Z&&!y.Pe(a)&&y.g.ca("Expected function but got %s: %s.",[y.U(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.g.hg=function(a,b,d){y.g.Z&&!y.jc(a)&&y.g.ca("Expected object but got %s: %s.",[y.U(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.g.cg=function(a,b,d){y.g.Z&&!y.isArray(a)&&y.g.ca("Expected array but got %s: %s.",[y.U(a),a],b,Array.prototype.slice.call(arguments,2));return a};
y.g.dg=function(a,b,d){y.g.Z&&!y.Oe(a)&&y.g.ca("Expected boolean but got %s: %s.",[y.U(a),a],b,Array.prototype.slice.call(arguments,2));return a};y.g.fg=function(a,b,d,f){!y.g.Z||a instanceof b||y.g.ca("instanceof check failed.",null,d,Array.prototype.slice.call(arguments,3));return a};y.c={};y.pa=y.wd;y.c.mh=function(a){return a[a.length-1]};y.c.p=Array.prototype;y.c.indexOf=y.pa&&y.c.p.indexOf?function(a,b,d){y.g.assert(null!=a.length);return y.c.p.indexOf.call(a,b,d)}:function(a,b,d){d=null==d?0:0>d?Math.max(0,a.length+d):d;if(y.B(a))return y.B(b)&&1==b.length?a.indexOf(b,d):-1;for(;d<a.length;d++)if(d in a&&a[d]===b)return d;return-1};
y.c.lastIndexOf=y.pa&&y.c.p.lastIndexOf?function(a,b,d){y.g.assert(null!=a.length);return y.c.p.lastIndexOf.call(a,b,null==d?a.length-1:d)}:function(a,b,d){d=null==d?a.length-1:d;0>d&&(d=Math.max(0,a.length+d));if(y.B(a))return y.B(b)&&1==b.length?a.lastIndexOf(b,d):-1;for(;0<=d;d--)if(d in a&&a[d]===b)return d;return-1};
y.c.forEach=y.pa&&y.c.p.forEach?function(a,b,d){y.g.assert(null!=a.length);y.c.p.forEach.call(a,b,d)}:function(a,b,d){for(var f=a.length,g=y.B(a)?a.split(""):a,h=0;h<f;h++)h in g&&b.call(d,g[h],h,a)};y.c.we=function(a,b){for(var d=y.B(a)?a.split(""):a,f=a.length-1;0<=f;--f)f in d&&b.call(void 0,d[f],f,a)};
y.c.filter=y.pa&&y.c.p.filter?function(a,b,d){y.g.assert(null!=a.length);return y.c.p.filter.call(a,b,d)}:function(a,b,d){for(var f=a.length,g=[],h=0,k=y.B(a)?a.split(""):a,l=0;l<f;l++)if(l in k){var n=k[l];b.call(d,n,l,a)&&(g[h++]=n)}return g};y.c.map=y.pa&&y.c.p.map?function(a,b,d){y.g.assert(null!=a.length);return y.c.p.map.call(a,b,d)}:function(a,b,d){for(var f=a.length,g=Array(f),h=y.B(a)?a.split(""):a,k=0;k<f;k++)k in h&&(g[k]=b.call(d,h[k],k,a));return g};
y.c.reduce=function(a,b,d,f){if(a.reduce)return f?a.reduce(y.bind(b,f),d):a.reduce(b,d);var g=d;y.c.forEach(a,function(d,k){g=b.call(f,g,d,k,a)});return g};y.c.reduceRight=function(a,b,d,f){if(a.reduceRight)return f?a.reduceRight(y.bind(b,f),d):a.reduceRight(b,d);var g=d;y.c.we(a,function(d,k){g=b.call(f,g,d,k,a)});return g};
y.c.some=y.pa&&y.c.p.some?function(a,b,d){y.g.assert(null!=a.length);return y.c.p.some.call(a,b,d)}:function(a,b,d){for(var f=a.length,g=y.B(a)?a.split(""):a,h=0;h<f;h++)if(h in g&&b.call(d,g[h],h,a))return!0;return!1};y.c.every=y.pa&&y.c.p.every?function(a,b,d){y.g.assert(null!=a.length);return y.c.p.every.call(a,b,d)}:function(a,b,d){for(var f=a.length,g=y.B(a)?a.split(""):a,h=0;h<f;h++)if(h in g&&!b.call(d,g[h],h,a))return!1;return!0};
y.c.count=function(a,b,d){var f=0;y.c.forEach(a,function(a,h,k){b.call(d,a,h,k)&&++f},d);return f};y.c.find=function(a,b,d){b=y.c.Kc(a,b,d);return 0>b?null:y.B(a)?a.charAt(b):a[b]};y.c.Kc=function(a,b,d){for(var f=a.length,g=y.B(a)?a.split(""):a,h=0;h<f;h++)if(h in g&&b.call(d,g[h],h,a))return h;return-1};y.c.Eg=function(a,b,d){b=y.c.je(a,b,d);return 0>b?null:y.B(a)?a.charAt(b):a[b]};
y.c.je=function(a,b,d){for(var f=y.B(a)?a.split(""):a,g=a.length-1;0<=g;g--)if(g in f&&b.call(d,f[g],g,a))return g;return-1};y.c.contains=function(a,b){return 0<=y.c.indexOf(a,b)};y.c.dc=function(a){return 0==a.length};y.c.clear=function(a){if(!y.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};y.c.insert=function(a,b){y.c.contains(a,b)||a.push(b)};y.c.Tc=function(a,b,d){y.c.splice(a,d,0,b)};y.c.Sg=function(a,b,d){y.ga(y.c.splice,a,d,0).apply(null,b)};
y.c.insertBefore=function(a,b,d){var f;2==arguments.length||0>(f=y.c.indexOf(a,d))?a.push(b):y.c.Tc(a,b,f)};y.c.remove=function(a,b){var d=y.c.indexOf(a,b),f;(f=0<=d)&&y.c.lb(a,d);return f};y.c.lb=function(a,b){y.g.assert(null!=a.length);return 1==y.c.p.splice.call(a,b,1).length};y.c.rh=function(a,b,d){b=y.c.Kc(a,b,d);return 0<=b?(y.c.lb(a,b),!0):!1};y.c.concat=function(a){return y.c.p.concat.apply(y.c.p,arguments)};
y.c.Hf=function(a){var b=a.length;if(0<b){for(var d=Array(b),f=0;f<b;f++)d[f]=a[f];return d}return[]};y.c.td=y.c.Hf;y.c.extend=function(a,b){for(var d=1;d<arguments.length;d++){var f=arguments[d],g;if(y.isArray(f)||(g=y.kb(f))&&Object.prototype.hasOwnProperty.call(f,"callee"))a.push.apply(a,f);else if(g)for(var h=a.length,k=f.length,l=0;l<k;l++)a[h+l]=f[l];else a.push(f)}};y.c.splice=function(a,b,d,f){y.g.assert(null!=a.length);return y.c.p.splice.apply(a,y.c.slice(arguments,1))};
y.c.slice=function(a,b,d){y.g.assert(null!=a.length);return 2>=arguments.length?y.c.p.slice.call(a,b):y.c.p.slice.call(a,b,d)};y.c.ph=function(a,b){for(var d=b||a,f={},g=0,h=0;h<a.length;){var k=a[h++],l=y.jc(k)?"o"+y.qb(k):(typeof k).charAt(0)+k;Object.prototype.hasOwnProperty.call(f,l)||(f[l]=!0,d[g++]=k)}d.length=g};y.c.Rc=function(a,b,d){return y.c.Sc(a,d||y.c.la,!1,b)};y.c.mg=function(a,b,d){return y.c.Sc(a,b,!0,void 0,d)};
y.c.Sc=function(a,b,d,f,g){for(var h=0,k=a.length,l;h<k;){var n=h+k>>1,q;q=d?b.call(g,a[n],n,a):b(f,a[n]);0<q?h=n+1:(k=n,l=!q)}return l?h:~h};y.c.sort=function(a,b){y.g.assert(null!=a.length);y.c.p.sort.call(a,b||y.c.la)};y.c.zh=function(a,b){for(var d=0;d<a.length;d++)a[d]={index:d,value:a[d]};var f=b||y.c.la;y.c.sort(a,function(a,b){return f(a.value,b.value)||a.index-b.index});for(d=0;d<a.length;d++)a[d]=a[d].value};y.c.xh=function(a,b,d){var f=d||y.c.la;y.c.sort(a,function(a,d){return f(a[b],d[b])})};
y.c.ah=function(a,b,d){b=b||y.c.la;for(var f=1;f<a.length;f++){var g=b(a[f-1],a[f]);if(0<g||0==g&&d)return!1}return!0};y.c.ue=function(a,b,d){if(!y.kb(a)||!y.kb(b)||a.length!=b.length)return!1;var f=a.length;d=d||y.c.te;for(var g=0;g<f;g++)if(!d(a[g],b[g]))return!1;return!0};y.c.compare=function(a,b,d){return y.c.ue(a,b,d)};y.c.wg=function(a,b,d){d=d||y.c.la;for(var f=Math.min(a.length,b.length),g=0;g<f;g++){var h=d(a[g],b[g]);if(0!=h)return h}return y.c.la(a.length,b.length)};
y.c.la=function(a,b){return a>b?1:a<b?-1:0};y.c.te=function(a,b){return a===b};y.c.kg=function(a,b,d){d=y.c.Rc(a,b,d);return 0>d?(y.c.Tc(a,b,-(d+1)),!0):!1};y.c.lg=function(a,b,d){b=y.c.Rc(a,b,d);return 0<=b?y.c.lb(a,b):!1};y.c.ng=function(a,b,d){for(var f={},g=0;g<a.length;g++){var h=a[g],k=b.call(d,h,g,a);y.Pc(k)&&(f[k]||(f[k]=[])).push(h)}return f};y.c.Gh=function(a,b,d){var f={};y.c.forEach(a,function(g,h){f[b.call(d,g,h,a)]=g});return f};
y.c.oh=function(a,b,d){var f=[],g=0,h=a;d=d||1;void 0!==b&&(g=a,h=b);if(0>d*(h-g))return[];if(0<d)for(a=g;a<h;a+=d)f.push(a);else for(a=g;a>h;a+=d)f.push(a);return f};y.c.repeat=function(a,b){for(var d=[],f=0;f<b;f++)d[f]=a;return d};y.c.ve=function(a){for(var b=[],d=0;d<arguments.length;d++){var f=arguments[d];y.isArray(f)?b.push.apply(b,y.c.ve.apply(null,f)):b.push(f)}return b};
y.c.rotate=function(a,b){y.g.assert(null!=a.length);a.length&&(b%=a.length,0<b?y.c.p.unshift.apply(a,a.splice(-b,b)):0>b&&y.c.p.push.apply(a,a.splice(0,-b)));return a};y.c.Qh=function(a){if(!arguments.length)return[];for(var b=[],d=0;;d++){for(var f=[],g=0;g<arguments.length;g++){var h=arguments[g];if(d>=h.length)return b;f.push(h[d])}b.push(f)}};y.c.wh=function(a,b){for(var d=b||Math.random,f=a.length-1;0<f;f--){var g=Math.floor(d()*(f+1)),h=a[f];a[f]=a[g];a[g]=h}};y.Af={};y.Af.Rf=function(){};y.m=function(){y.m.mc!=y.m.nc.dd&&(y.m.na[y.qb(this)]=this)};y.m.nc={dd:0,Ue:1,Sf:2};y.m.mc=0;y.m.na={};y.m.Ng=function(){var a=[],b;for(b in y.m.na)y.m.na.hasOwnProperty(b)&&a.push(y.m.na[Number(b)]);return a};y.m.tg=function(){y.m.na={}};y.m.prototype.pc=!1;y.m.prototype.isDisposed=function(){return this.pc};
y.m.prototype.yb=function(){if(!this.pc&&(this.pc=!0,this.bc(),y.m.mc!=y.m.nc.dd)){var a=y.qb(this);if(y.m.mc==y.m.nc.Ue&&!y.m.na.hasOwnProperty(a))throw Error(this+" did not call the goog.Disposable base constructor or was disposed of after a clearUndisposedObjects call");delete y.m.na[a]}};y.m.prototype.bc=function(){if(this.Ad)for(;this.Ad.length;)this.Ad.shift()()};y.m.isDisposed=function(a){return a&&"function"==typeof a.isDisposed?a.isDisposed():!1};
y.yb=function(a){a&&"function"==typeof a.yb&&a.yb()};y.rf=function(a){for(var b=0,d=arguments.length;b<d;++b){var f=arguments[b];y.kb(f)?y.rf.apply(null,f):y.yb(f)}};y.h={};y.h.ob=function(){y.m.call(this);this.N=[];this.Q={}};y.F(y.h.ob,y.m);c=y.h.ob.prototype;c.od=1;c.gb=0;c.j=function(a,b,d){var f=this.Q[a];f||(f=this.Q[a]=[]);var g=this.od;this.N[g]=a;this.N[g+1]=b;this.N[g+2]=d;this.od=g+3;f.push(g);return g};c.ld=function(a,b,d){if(a=this.Q[a]){var f=this.N;if(a=y.c.find(a,function(a){return f[a+1]==b&&f[a+2]==d}))return this.xa(a)}return!1};
c.xa=function(a){if(0!=this.gb)return this.Ga||(this.Ga=[]),this.Ga.push(a),!1;var b=this.N[a];if(b){var d=this.Q[b];d&&y.c.remove(d,a);delete this.N[a];delete this.N[a+1];delete this.N[a+2]}return!!b};c.r=function(a,b){var d=this.Q[a];if(d){this.gb++;for(var f=y.c.slice(arguments,1),g=0,h=d.length;g<h;g++){var k=d[g];this.N[k+1].apply(this.N[k+2],f)}this.gb--;if(this.Ga&&0==this.gb)for(;d=this.Ga.pop();)this.xa(d)}};
c.clear=function(a){if(a){var b=this.Q[a];b&&(y.c.forEach(b,this.xa,this),delete this.Q[a])}else this.N.length=0,this.Q={}};c.$a=function(a){if(a){var b=this.Q[a];return b?b.length:0}a=0;for(b in this.Q)a+=this.$a(b);return a};c.bc=function(){y.h.ob.Ma.bc.call(this);delete this.N;delete this.Q;delete this.Ga};e.o={};e.o.v=function(){this.h=new y.h.ob};var z=function(){return"false"!=e.nb().getItem("send_usage")};e.o.v.prototype.xa=function(a){return this.h.xa(a)};y.D={};y.D.lf=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};y.D.parse=function(a){a=String(a);if(y.D.lf(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};y.D.ff=function(a){return eval("("+a+")")};y.D.qc=function(a,b){return(new y.D.da(b)).qc(a)};
y.D.da=function(a){this.Bb=a};y.D.da.prototype.qc=function(a){var b=[];A(this,a,b);return b.join("")};
var A=function(a,b,d){switch(typeof b){case "string":B(b,d);break;case "number":d.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":d.push(b);break;case "undefined":d.push("null");break;case "object":if(null==b){d.push("null");break}if(y.isArray(b)){var f=b.length;d.push("[");for(var g="",h=0;h<f;h++)d.push(g),g=b[h],A(a,a.Bb?a.Bb.call(b,String(h),g):g,d),g=",";d.push("]");break}d.push("{");f="";for(h in b)Object.prototype.hasOwnProperty.call(b,h)&&(g=b[h],"function"!=typeof g&&(d.push(f),
B(h,d),d.push(":"),A(a,a.Bb?a.Bb.call(b,h,g):g,d),f=","));d.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};y.D.da.sc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};y.D.da.cf=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
var B=function(a,b){b.push('"',a.replace(y.D.da.cf,function(a){if(a in y.D.da.sc)return y.D.da.sc[a];var b=a.charCodeAt(0),g="\\u";16>b?g+="000":256>b?g+="00":4096>b&&(g+="0");return y.D.da.sc[a]=g+b.toString(16)}),'"')};e.w=function(a,b,d,f){window.trackEvent&&window.trackEvent(a,b,d,f)};e.n=function(a){this.t=a;a=y.bind(this.ma,this);this.t.h.j("collection_enabled_changed",a,void 0);this.mb=z()?this.j():[]};e.n.prototype.j=function(){return[]};e.n.prototype.ld=function(){for(var a=0;a<this.mb.length;a++)this.t.xa(this.mb[a]);this.mb=[]};e.n.prototype.ma=function(a){a?this.mb=this.j():this.ld()};
e.T=function(a,b,d,f){this.tc=b;this.fd="EpochCounter_"+d;this.ub=f;C(this,"epochEventCounts")||(D(this,"epochEventCounts",{}),D(this,"firstEpochStart",a),b=E(this),D(this,"lastEpochReported",b-1));this.md();(function(b){setTimeout(function(){setInterval(y.bind(e.T.prototype.md,b),b.tc)},(Date.now()-a)%b.tc+e.T.df)})(this)};e.T.df=5E3;
var C=function(a,b){return y.D.ff(e.nb().getItem(a.fd+"."+b))},D=function(a,b,d){e.nb().setItem(a.fd+"."+b,y.D.qc(d))},E=function(a){var b=Date.now();return Math.floor((b-C(a,"firstEpochStart"))/a.tc)},G=function(a){var b=!z();a.M=b},H=function(a){var b=E(a),d=C(a,"epochEventCounts");d.hasOwnProperty(b)||(d[b]=0);d[b]++;D(a,"epochEventCounts",d)};
e.T.prototype.md=function(){var a=E(this),b=C(this,"epochEventCounts"),d=C(this,"lastEpochReported");if(!this.M)for(d+=1;d<a;d++){var f=d,g=b,h={},k=void 0;for(k in g)if(!(k>f))for(var l in this.ub)f-k+1<=l&&(h[l]=h[l]||0,h[l]+=g[k]);for(l in this.ub)if(f=h[l])this.ub[l](f)}l=-Infinity;for(var n in this.ub)l=Math.max(l,n);n=a-l+1;for(var q in b)q<n&&delete b[q];D(this,"epochEventCounts",b);D(this,"lastEpochReported",a-1)};y.b.format=function(a,b){var d=Array.prototype.slice.call(arguments),f=d.shift();if("undefined"==typeof f)throw Error("[goog.string.format] Template required");return f.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,f,l,n,q,F,t){if("%"==q)return"%";var r=d.shift();if("undefined"==typeof r)throw Error("[goog.string.format] Not enough arguments");arguments[0]=r;return y.b.format.Y[q].apply(null,arguments)})};y.b.format.Y={};
y.b.format.Y.s=function(a,b,d){return isNaN(d)||""==d||a.length>=d?a:a=-1<b.indexOf("-",0)?a+y.b.repeat(" ",d-a.length):y.b.repeat(" ",d-a.length)+a};
y.b.format.Y.f=function(a,b,d,f,g){f=a.toString();isNaN(g)||""==g||(f=a.toFixed(g));var h;h=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(f=h+f);if(isNaN(d)||f.length>=d)return f;f=isNaN(g)?Math.abs(a).toString():Math.abs(a).toFixed(g);a=d-f.length-h.length;0<=b.indexOf("-",0)?f=h+f+y.b.repeat(" ",a):(b=0<=b.indexOf("0",0)?"0":" ",f=h+y.b.repeat(b,a)+f);return f};y.b.format.Y.d=function(a,b,d,f,g,h,k,l){return y.b.format.Y.f(parseInt(a,10),b,d,f,0,h,k,l)};y.b.format.Y.i=y.b.format.Y.d;
y.b.format.Y.u=y.b.format.Y.d;e.notifications.l=function(a,b,d){this.Xa=a;this.X=b;this.ta=e.notifications.k.LOADING;this.Dc=!1;this.L=0;this.aa="";this.zc=!1;this.Ya=this.Ea=null;this.ja=e.notifications.Lb;this.ea=null;this.Cc="";this.Ba=this.Db=this.ra=null;this.ua="";this.Fa=this.O=null;this.V=new e.notifications.o.v;this.Cb=[new e.notifications.e.fa(this.V),new e.notifications.e.I(this.V),new e.notifications.e.P(this.V)];this.G=new e.notifications.Iframe(this.Xa,this.X,d,e.bind(this.Mb,this),e.bind(this.ha,this,e.notifications.k.Ua),
e.bind(this.ha,this,e.notifications.k.Kb))};y.Ra("crx.notifications.Background",e.notifications.l);e.notifications.l.Uc=27E5;e.notifications.l.Xf="#999";e.notifications.l.Yf="#fff";var I=function(a){chrome.extension.onConnect.addListener(e.bind(a.tf,a));chrome.browserAction.onClicked.addListener(function(){a.Dc||a.Ca(!0,500)})};
e.notifications.l.prototype.tf=function(a){var b=this;"popup"==a.name&&(a.onMessage.addListener(function(a){"newCountPolled"==a.name&&b.Mb(a.newCount,a.newDisplayText)}),this.O=a,this.Ca(!1),a.onDisconnect.addListener(function(){b.Ca(!0,500);b.O=null}),this.V.fb())};
e.notifications.l.prototype.Jd=function(a){var b=this;"sync"==a.name&&(a.sender&&a.sender.id&&a.sender.id==window.location.host)&&(this.Fa&&this.Fa.disconnect(),this.Fa=a,a.onMessage.addListener(function(a){var f=a.cnt;a=a.cntTxt;b.ta!=e.notifications.k.ab?b.ta!=e.notifications.k.LOADING&&J(b,500):b.Mb(parseInt(f,10),a)}),a.onDisconnect.addListener(function(a){a==b.Fa&&(b.Fa=null)}))};
e.notifications.l.prototype.Fb=function(a,b,d){a&&("isStatsCollectionEnabled"==a.msg?d(z()):"setStatsCollectionEnabled"==a.msg?(b=this.V,a=a.enabled,z()!=a&&(e.nb().setItem("send_usage",a?"true":"false"),b.h.r("collection_enabled_changed",a))):"retryNowClicked"==a.msg&&this.V.h.r("retry_now_clicked"))};e.notifications.l.prototype.Id=function(a,b,d){if(a){if("getVersion"==a.msg&&d)try{var f={version:chrome.app.getDetails().version};d(f);return}catch(g){}d&&d()}};
var K=function(a){if(a.ea){var b="",d;switch(a.ta){case e.notifications.k.ab:0===a.L?(d=a.zc?a.Db:a.Ba,a.ua=chrome.i18n.getMessage("no_new_notifications")):(b=a.aa,d=a.Db,a.ua=1==a.L?chrome.i18n.getMessage("one_new_notification"):chrome.i18n.getMessage("many_new_notifications",[a.L]));break;case e.notifications.k.Ua:d=a.Ba;a.ua=chrome.i18n.getMessage("sign_in_tooltip");break;case e.notifications.k.Kb:d=a.Ba;a.ua=chrome.i18n.getMessage("error_tooltip");break;case e.notifications.k.LOADING:d=a.Ba;a.ua=
chrome.i18n.getMessage("loading");break;default:return}var f=a.ea.width,g=a.ea.height;a.ra.save();a.ra.clearRect(0,0,f,g);a.ra.drawImage(d,0,0);a.ra.restore();a.Cc=b;chrome.windows.getAll({populate:!0},function(b){for(var d=0;d<b.length;d++)for(var f=b[d],g=0;g<f.tabs.length;g++)a.yc(f.tabs[g].id)})}};
e.notifications.l.prototype.yc=function(a){var b=this.ra.getImageData(0,0,this.ea.width,this.ea.height);chrome.browserAction.setIcon({imageData:b,tabId:a});chrome.browserAction.setTitle({title:this.ua,tabId:a});chrome.browserAction.setBadgeText({text:this.Cc,tabId:a});chrome.browserAction.setBadgeBackgroundColor({color:"#DB4437"})};e.notifications.l.prototype.Eb=function(a){a.cookie.name==e.notifications.bb&&a.cookie.domain==e.notifications.cb&&J(this,500)};
var J=function(a,b){a.Ea&&clearTimeout(a.Ea);a.Ea=null;a.Ve=b;if(0<b){var d=Math.max(b-1E3,0);a.Ea=setTimeout(function(){a.Ea=null;J(a,d)},b-d)}else try{chrome.cookies.getAll({name:e.notifications.bb,domain:e.notifications.cb},function(b){b&&b.length&&1>b.length?a.ha(e.notifications.k.Ua):a.ha(e.notifications.k.LOADING)})}catch(f){a.ha(e.notifications.k.LOADING)}};e.notifications.l.prototype.vc=function(a){this.G.vc(a)};y.qa(e.notifications.l.prototype,"setIsPolling",e.notifications.l.prototype.vc);
e.notifications.l.prototype.Ca=function(a,b){this.Ya&&clearTimeout(this.Ya);this.Ya=null;b?this.Ya=setTimeout(e.bind(this.Ca,this,a),b):(this.Dc=a)?chrome.browserAction.setPopup({popup:"popup.html"}):chrome.browserAction.setPopup({popup:""})};e.notifications.l.prototype.Mb=function(a,b,d){console.log("Updating count.");this.L=a;this.aa=b;void 0!==d&&(this.zc=d);this.V.h.r("count_updated",this.L,this.aa);this.ha(e.notifications.k.ab);console.log("Done updating count.")};
e.notifications.l.prototype.ha=function(a){switch(a){case e.notifications.k.LOADING:w(this.G);this.G.load({},{notsbg:"1"});break;case e.notifications.k.Kb:w(this.G);var b=1+(Math.random()-0.5);J(this,this.ja*b);this.ja*=2;this.ja>e.notifications.l.Uc&&(this.ja=e.notifications.l.Uc);break;case e.notifications.k.Ua:w(this.G);this.ja=e.notifications.Lb;break;case e.notifications.k.ab:this.ja=e.notifications.Lb;break;default:return}b=this.ta!=a;this.ta=a;K(this);b&&this.O&&this.O.postMessage({content:"STATE_CHANGED"})};
y.qa(e.notifications.l.prototype,"switchToState",e.notifications.l.prototype.ha);e.notifications.l.prototype.xd=function(){return this.ta};y.qa(e.notifications.l.prototype,"getState",e.notifications.l.prototype.xd);e.notifications.l.prototype.Cf=function(){return this.Ve};y.qa(e.notifications.l.prototype,"getTimeUntilNextReloadMs",e.notifications.l.prototype.Cf);
e.notifications.yd=function(){var a,b=e.notifications.A.create(!1),d=new e.notifications.l("notifications-target",b,new e.a.Hd);window.controller=d;if(e.notifications.Va){var f=new e.a.Ib(b);a=new e.a.H(f);window.tabManager=a}document.addEventListener("DOMContentLoaded",function(){b.init();d.ea=document.getElementById("canvas");d.ra=d.ea.getContext("2d");d.Db=document.getElementById("icon");d.Ba=document.getElementById("icon-no-notifications");d.G.init();d.Ca(!0);chrome.extension.onRequest.addListener(e.bind(d.Fb,
d));chrome.extension.onRequestExternal.addListener(e.bind(d.Id,d));chrome.cookies.onChanged.addListener(e.bind(d.Eb,d));chrome.tabs.onUpdated.addListener(e.bind(d.yc,d));I(d);chrome.extension.onConnect.addListener(e.bind(d.Jd,d));J(d,250);var f=new e.notifications.e.R(d.V),g=new e.notifications.e.Wa(d.V,f);d.Cb.push(g);e.notifications.Va&&a.Cb.push(new e.a.e.Da(a.q,f))},!1);var g=g||[];g.push(["_setAccount","UA-28105449-1"]);(function(){var a=document.createElement("script");a.type="text/javascript";
a.async=!0;a.src="https://ssl.google-analytics.com/ga.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();window._gaq=g};y.Ra("crx.notifications.main",e.notifications.yd);y.Ra("trackEvent",function(a,b,d,f){window._gaq&&window._gaq.push(["_trackEvent",a,b,d,f])});e.a.Sa=function(a){this.pb="AIzaSyAgFxxGy4ZxzeLjNCzr098glYjbU4agIcI";this.sf="https://www.googleapis.com/plus/v1/people/";this.Ic=a};e.a.Sa.Td="https://plus.google.com/";e.a.Sa.prototype.getData=function(a,b,d){var f=this;L(this,a,function(g){g&&(f.Ic.Yc?M(f,a,b,function(a){var b=!1,f=!1;a&&(b=!!a.is_following,f=!!a.is_linked_to_page);g.isFollowing=b;g.isVerified=f;d(g)}):(g.isFollowing=!1,d(g)))})};
var L=function(a,b,d){var f=new XMLHttpRequest;f.onreadystatechange=function(){if(4==f.readyState)if(200!=f.status)console.log("Profile data fetch failed. Error code:"+f.status);else{var a=JSON.parse(f.responseText);a.error?console.error("Google+ API Error:",a.error,f):d(a)}};f.open("GET",a.sf+b+"?key="+a.pb,!0);f.send()},M=function(a,b,d,f){a.Ic.makeRequest(d,e.a.Sa.Td+b,f)};e.a.Qd=/^http:\/\/.+/;e.a.Rd={permissions:["tabs"],origins:["http://*/*"]};e.a.Kd=[60,146,0,255];e.a.Ld=[219,75,47,255];
e.a.H=function(a){this.C={};this.Bd=new e.a.Sa(a);this.q=new e.a.o.v;this.Cb=[new e.a.e.fa(this.q),new e.a.e.W(this.q),new e.a.e.ba(this.q)];this.K=new e.Hb;chrome.extension.onRequest.addListener(e.bind(this.Fb,this));chrome.tabs.onActiveChanged.addListener(e.bind(this.Gd,this));chrome.cookies.onChanged.addListener(e.bind(this.Eb,this));e.a.Dd()?"true"!=window.localStorage.getItem(e.a.Gb)?"true"==window.localStorage.getItem(e.a.Ta)?chrome.tabs.query({windowId:chrome.windows.WINDOW_ID_CURRENT,active:!0},
e.bind(this.Cd,this)):chrome.extension.inIncognitoContext||(setTimeout(e.bind(this.q.Fd,this.q),1E4),chrome.tabs.create({url:chrome.extension.getURL("followpromo.html")}),window.localStorage.setItem(e.a.Gb,"true")):N()==e.a.k.sa&&this.init():setTimeout(e.bind(this.q.Ed,this.q),1E4)};y.Ra("crx.pluspages.TabManager",e.a.H);
e.a.H.prototype.init=function(){this.K.register(chrome.extension.onConnect,e.bind(this.jf,this));this.K.register(chrome.tabs.onUpdated,e.bind(this.hf,this));this.K.register(chrome.tabs.onRemoved,e.bind(this.gf,this))};y.qa(e.a.H.prototype,"init",e.a.H.prototype.init);e.a.H.prototype.Zb=function(){this.O&&(this.O.postMessage({disconnect:!0}),this.O=null);for(var a in this.C){var b=this.C[a];b.port&&b.port.postMessage({disconnect:!0})}a=this.K;for(var d in a.K)a.K[d].$e(),delete a.K[d];this.C={}};
y.qa(e.a.H.prototype,"cleanup",e.a.H.prototype.Zb);c=e.a.H.prototype;c.Cd=function(a){for(var b in a)O(this,a[b].id)};c.Eb=function(a){a.cookie.name==e.a.bb&&a.cookie.domain==e.a.cb&&(a.removed?this.Zb():(this.Zb(),this.init()))};c.jf=function(a){"page"==a.name?P(this,a):"plus_follow_popup"==a.name&&Q(this,a)};c.gf=function(a){delete this.C[a]};c.Gd=function(a){"true"==window.localStorage.getItem(e.a.Ta)?O(this,a):N()==e.a.k.sa?R(this,S(this,a),a):chrome.browserAction.setBadgeText({text:"",tabId:a})};
var P=function(a,b){a.C[b.sender.tab.id]={port:b,ka:null};a.K.register(b.onDisconnect,function(){delete a.C[b.sender.tab.id]});a.K.register(b.onMessage,e.bind(a.bf,a,b.sender.tab.id,b.sender.tab.url))},Q=function(a,b){a.O=b;a.q.fb();a.K.register(b.onDisconnect,function(){a.O=null});chrome.tabs.query({windowId:chrome.windows.WINDOW_ID_CURRENT,active:!0},function(d){for(var f in d){var g=d[f];S(a,g.id)&&b&&(a.q.h.r("button_clicked_with_badge"),b.postMessage({profileData:a.C[g.id].ka}))}})};
e.a.H.prototype.hf=function(a,b,d){e.a.Qd.test(d.url)&&"loading"!=b.status&&chrome.permissions.contains(e.a.Rd,function(b){if(b)try{chrome.tabs.executeScript(a,{file:"js/pluspage_content_script.js"})}catch(d){e.S(d)}})};
e.a.H.prototype.Fb=function(a){a&&("plusFollowActivated"==a.msg?this.q.h.r("plus_follow_activated"):"pageLoadNoPlusPage"==a.msg?this.q.h.r("page_loaded",!1,!1):"plusFollowPromoClick"==a.msg?(chrome.tabs.query({windowId:chrome.windows.WINDOW_ID_CURRENT,active:!0},function(a){for(var d in a)chrome.browserAction.setBadgeText({text:"",tabId:a[d].id})}),this.q.fb()):"plusFollowPromoPageOpened"==a.msg&&this.q.h.r("popup_promo_link_clicked"))};
var S=function(a,b){return N()!=e.a.k.sa?(e.S("Error: +Follow is not enabled, but TabManager is running"),!1):!!(a.C[b]&&a.C[b].ka&&a.C[b].ka.isVerified)};e.a.H.prototype.bf=function(a,b,d){"maybeshow"==d.action?(d=d.profileId,this.Bd.getData(d,b,e.bind(this.Md,this,a,d))):"badge_action"==d.action&&(window.localStorage.setItem(d.profileId,d.badgeState),d.badgeState==e.a.Za.Ec?this.q.h.r("plus_follow_tab_expanded"):d.badgeState==e.a.Za.CLOSED&&this.q.h.r("plus_follow_tab_closed"))};
e.a.H.prototype.Md=function(a,b,d){this.C[a].ka=d;N()!=e.a.k.sa?(e.S("Error: +Follow is not enabled, but TabManager is running"),b=!1):this.C[a]&&this.C[a].ka&&this.C[a].ka.isVerified?(b=window.localStorage.getItem(b),b=b==e.a.Za.Ec||b==e.a.Za.CLOSED||this.C[a].ka.isFollowing?!1:!0):b=!1;this.q.h.r("page_loaded",!0,b);b&&this.C[a].port.postMessage({profileData:d});if(b=S(this,a))this.q.h.r("extension_badged",!1),this.O&&this.O.postMessage({profileData:d});R(this,b,a)};
var R=function(a,b,d){chrome.browserAction.setBadgeText({text:b?"+":"",tabId:d});chrome.browserAction.setBadgeBackgroundColor({color:e.a.Kd,tabId:d});a.q.h.r("browser_action_updated",b?e.a.ia.Ac:e.a.ia.Jb)},O=function(a,b){a.q.h.r("extension_badged",!0);a.q.h.r("browser_action_updated",e.a.ia.Bc);chrome.browserAction.setBadgeText({text:"+",tabId:b});chrome.browserAction.setBadgeBackgroundColor({color:e.a.Ld,tabId:b})},N=function(){var a=window.localStorage.getItem(e.a.Vb);return a==e.a.k.sa||a==e.a.k.Tb?
a:null};e.a.Ib=function(a){this.X=a;this.Vc="APISID";this.ic="SAPISID";this.$c="__OVERRIDE_SID";this.gc="__APISID";this.hc="__SAPISID";this.Ne="googleapis.config/auth/useFirstPartyAuth";this.Le="googleapis.config/root";this.Me="googleapis.config/root-1p";this.ad="https://clients6.google.com";this.pb="AIzaSyAgFxxGy4ZxzeLjNCzr098glYjbU4agIcI";this.Yc=!1;T(this);this.X.Ha&&this.X.ya?this.bd():u(this.X,"firstParty",e.bind(this.bd,this),e.bind(this.Se,this));chrome.cookies.onChanged.addListener(y.bind(this.Re,
this))};c=e.a.Ib.prototype;c.Se=function(){e.S("Gapi Load Failed")};c.makeRequest=function(a,b,d){gapi.client.request({path:"/plus/v1whitelisted/rpc/isSiteLinked",headers:{"Content-Type":"application/json"},method:"GET",params:{key:this.pb,nolog:!0,pageUrl:b,siteUrl:a}}).execute(function(a){d(a)})};c.Gf=function(){gapi.config.update(this.Ne,!0);gapi.config.update(this.Le,this.ad);gapi.config.update(this.Me,this.ad);gapi.client.setApiKey(this.pb);gapi.client.register("plus.rpc.isSiteLinked",{apiVersion:"v1whitelisted"})};
c.bd=function(){gapi.load("client",e.bind(this.Gf,this))};c.rd=function(a){a&&(a.name==this.Vc?window[this.gc]=a.value:a.name==this.ic&&(window[this.hc]=a.value));window[this.$c]=!!window[this.hc]||!!window[this.gc];this.Yc=!!window[this.$c]};var T=function(a){window[a.gc]=null;window[a.hc]=null;chrome.cookies.get({url:"http://www.google.com",name:a.Vc},y.bind(a.rd,a));chrome.cookies.get({url:"https://www.google.com",name:a.ic},y.bind(a.rd,a))};
e.a.Ib.prototype.Re=function(a){0<=a.cookie.domain.indexOf("google.")&&a.cookie.name==this.ic&&T(this)};e.a.o={};e.a.o.v=function(){e.o.v.call(this)};y.F(e.a.o.v,e.o.v);e.a.o.v.prototype.Ed=function(){this.h.r("plus_follow_not_offered")};e.a.o.v.prototype.Fd=function(){this.h.r("plus_follow_offered")};e.a.o.v.prototype.Ka=function(a,b){return this.h.j("button_clicked",a,b)};e.a.o.v.prototype.fb=function(){this.h.r("button_clicked")};e.a.e={};e.a.e.fa=function(a){e.n.call(this,a)};y.F(e.a.e.fa,e.n);
e.a.e.fa.prototype.j=function(){return[this.t.h.j("button_clicked_with_badge",function(){e.w("plus_follow","open_popup_with_badge")},void 0),this.t.h.j("plus_follow_not_offered",function(){e.w("plus_follow","not_offered")},void 0),this.t.h.j("plus_follow_activated",function(){e.w("plus_follow","activated")},void 0),this.t.h.j("plus_follow_offered",function(){e.w("plus_follow","offered")},void 0),this.t.h.j("plus_follow_tab_expanded",function(){e.w("plus_follow","expand_tab")},void 0),this.t.h.j("plus_follow_tab_closed",
function(){e.w("plus_follow","close_tab")},void 0),this.t.h.j("popup_promo_link_clicked",function(){e.w("plus_follow","popup_promo_link_clicked")},void 0)]};e.a.e.ba=function(a){e.n.call(this,a);a=Date.now();this.Qb=new e.T(a,e.a.e.ba.va,"badging.extensionBadgedCount",{1:y.ga(e.w,"plus_follow","extension_badged","badge")});this.Rb=new e.T(a,e.a.e.ba.va,"badging.extensionBadgedPromoCount",{1:y.ga(e.w,"plus_follow","extension_badged","promo")});a=!z();this.Qb.M=a;a=!z();this.Rb.M=a};y.F(e.a.e.ba,e.n);
e.a.e.ba.va=864E5;e.a.e.ba.prototype.j=function(){var a=y.bind(this.Be,this);return[this.t.h.j("extension_badged",a,void 0)]};e.a.e.ba.prototype.ma=function(a){e.n.prototype.ma.call(this,a);a=!z();this.Qb.M=a;a=!z();this.Rb.M=a};e.a.e.ba.prototype.Be=function(a){a?H(this.Rb):H(this.Qb)};
e.a.e.W=function(a){e.n.call(this,a);a=Date.now();this.Pb=new e.T(a,e.a.e.W.va,"PageLoad.pageLoadNoBadgeCount",{1:y.ga(e.w,"plus_follow","page_load","no_badge")});this.Nb=new e.T(a,e.a.e.W.va,"PageLoad.pageLoadBadgeNotShownCount",{1:y.ga(e.w,"plus_follow","page_load","badge_not_shown")});this.Ob=new e.T(a,e.a.e.W.va,"PageLoad.pageLoadBadgeShownCount",{1:y.ga(e.w,"plus_follow","page_load","badge_shown")});a=!z();this.Pb.M=a;a=!z();this.Nb.M=a;a=!z();this.Ob.M=a};y.F(e.a.e.W,e.n);e.a.e.W.va=864E5;
e.a.e.W.prototype.j=function(){var a=y.bind(this.Ce,this);return[this.t.h.j("page_loaded",a,void 0)]};e.a.e.W.prototype.ma=function(a){e.n.prototype.ma.call(this,a);a=!z();this.Pb.M=a;a=!z();this.Nb.M=a;a=!z();this.Ob.M=a};e.a.e.W.prototype.Ce=function(a,b){a?b?H(this.Ob):H(this.Nb):H(this.Pb)};e.a.e.Da=function(a,b){e.n.call(this,a);this.Fc=e.a.ia.Jb;this.wa=b};y.F(e.a.e.Da,e.n);
e.a.e.Da.prototype.j=function(){var a=e.bind(this.ze,this);return[this.t.h.j("browser_action_updated",a,void 0),this.t.Ka(e.bind(this.La,this))]};e.a.e.Da.prototype.ze=function(a){this.Fc=a};
e.a.e.Da.prototype.La=function(){var a,b;switch(this.Fc){case e.a.ia.Ac:a="notification_count_on_click_badged";b=e.notifications.e.R.Sb(this.wa.aa);break;case e.a.ia.Bc:a="notification_count_on_click_promo";b=e.notifications.e.R.Sb(this.wa.aa);break;case e.a.ia.Jb:return;default:return}e.w("notifications",a,b,this.wa.$a())};e.notifications.o={};e.notifications.o.hd=function(a){this.Ke=a;this.L=void 0;U(a,e.bind(this.rc,this))};e.notifications.o.hd.prototype.rc=function(a){a&&!this.L&&this.Ke.h.r("button_activated",void 0===this.L);this.L=a};e.notifications.o.v=function(){e.o.v.call(this);new e.notifications.o.hd(this)};y.F(e.notifications.o.v,e.o.v);var U=function(a,b){return a.h.j("count_updated",b,void 0)};e.notifications.o.v.prototype.Ka=function(a,b){return this.h.j("button_clicked",a,b)};
e.notifications.o.v.prototype.fb=function(){this.h.r("button_clicked")};e.notifications.e={};y.Ra("crx.notifications.trackers",e.notifications.e);e.notifications.e.R=function(a){e.n.call(this,a);this.L=0;this.aa="not_updated"};y.F(e.notifications.e.R,e.n);y.qa(e.notifications.e,"NotificationCountTracker",e.notifications.e.R);e.notifications.e.R.prototype.j=function(){return[U(this.t,e.bind(this.rc,this))]};e.notifications.e.R.prototype.rc=function(a,b){this.L=a;this.aa=b};
e.notifications.e.R.Sb=function(a){if(a.match(/^\s*\d+\s*$/))return y.b.format("%02d",a);var b=a.match(/(\d+)/);return b?y.b.format("%02d+",b[1]):a};e.notifications.e.R.prototype.$a=function(){return this.L};e.notifications.e.Wa=function(a,b){e.n.call(this,a);this.wa=b};y.F(e.notifications.e.Wa,e.n);e.notifications.e.Wa.prototype.j=function(){return[this.t.Ka(e.bind(this.La,this))]};
e.notifications.e.Wa.prototype.La=function(){var a=e.notifications.e.R.Sb(this.wa.aa);e.w("notifications","notification_count_on_click",a,this.wa.$a())};e.notifications.e.fa=function(a){e.n.call(this,a)};y.F(e.notifications.e.fa,e.n);e.notifications.e.fa.prototype.j=function(){return[this.t.h.j("retry_now_clicked",function(){e.w("notifications","retry_now_clicked")},void 0)]};e.notifications.e.I=function(a){e.n.call(this,a);this.hb=this.ib=void 0};y.F(e.notifications.e.I,e.n);
e.notifications.e.I.qe="startup_activation_to_click_delay";e.notifications.e.I.re="activation_to_click_delay";e.notifications.e.I.prototype.j=function(){var a=e.bind(this.ye,this);return[this.t.h.j("button_activated",a,void 0),this.t.Ka(e.bind(this.La,this))]};e.notifications.e.I.prototype.ye=function(a){this.hb=a;this.ib=Date.now()};
e.notifications.e.I.Ae=[{za:60,label:"a: 0-1 minute"},{za:300,label:"b: 1-5 minutes"},{za:3600,label:"c: 5 minutes - 1 hour"},{za:86400,label:"d: 1 hour - 1 day"},{za:604800,label:"e: 1 day - 1 week"},{za:Infinity,label:"f: > 1 week"}];e.notifications.e.I.xe=function(){return e.notifications.e.I.Ae};e.notifications.e.I.se=function(a){for(var b=e.notifications.e.I.xe(),d=0;d<b.length;d++)if(a<b[d].za)return b[d].label;e.S("error in specification of click delay reporting thresholds");return"unknown"};
e.notifications.e.I.prototype.La=function(){if(void 0!==this.ib&&void 0!==this.hb){var a=e.notifications.e.I,b=(Date.now()-this.ib)/1E3,d=a.se(b);e.w("notifications",this.hb?a.qe:a.re,d,Math.round(b));this.hb=this.ib=void 0}};e.notifications.e.P=function(a){e.n.call(this,a);a=Date.now();var b={};e.notifications.e.P.ae.forEach(function(a){var f=e.notifications.e.P.be(a);b[a]=function(){e.w("notifications","active",f)}});this.Yb=new e.T(a,e.notifications.e.P.$d,"Activity.counter",b);G(this.Yb)};
y.F(e.notifications.e.P,e.n);e.notifications.e.P.$d=864E5;e.notifications.e.P.ae=[1,7,14,30];e.notifications.e.P.prototype.j=function(){return[this.t.Ka(e.bind(this.ef,this))]};e.notifications.e.P.prototype.ma=function(a){e.n.prototype.ma.call(this,a);a=!z();this.Yb.M=a};e.notifications.e.P.be=function(a){return a+" day"+(1==a?"":"s")};e.notifications.e.P.prototype.ef=function(){H(this.Yb)};e.notifications.yd();
