var crx=crx||{};window.crx=crx;crx.B=function(a){console.log(Date.now()+": "+a)};crx.ga=function(){};crx.A=function(a){crx.B(a);throw Error(a);};crx.bind=function(a,b,d){return a.call.apply(a.bind,arguments)};crx.$a="mjmiijggifbmmlmdlkoekhpmlbofhnnn";crx.I=function(){this.n=this.k=null;this.ta()};crx.I.bb=1E4;crx.I.prototype.ta=function(){this.k&&clearTimeout(this.k);this.k=null;this.n=chrome.extension.connect(crx.$a);this.n.onDisconnect.addListener(crx.bind(this.ab,this))};crx.I.prototype.ab=function(){this.k&&clearTimeout(this.k);this.k=null;this.k=setTimeout(crx.bind(this.ta,this),crx.I.bb)};crx.U=function(){this.j=[]};crx.U.prototype.register=function(a,b){a.addListener(b);var d={Xa:c(a,b)};this.j.push(d);return d};var c=function(a,b){return function(){a.removeListener(b)}};crx.ListenerRegistry=crx.U;crx.i18n=crx.i18n||{};crx.i18n.Z=function(a){a=a||{};for(var b=document.querySelectorAll("[i18n-content]"),d,e=0;d=b[e];e++){var f=d.getAttribute("i18n-content");if(f)var g=chrome.i18n.getMessage.apply(null,[f].concat(a[f]||[]));g&&(d.innerHTML=g)}};crx.i18n.Jb=function(a){crx.i18n.Z(a);document.dir=chrome.i18n.getMessage("@@bidi_dir")};crx.i18n=crx.i18n;crx.i18n.translateDom=crx.i18n.Z;crx.i18n.updateDom=crx.i18n.Jb;crx.notifications=crx.notifications||{};crx.notifications=crx.notifications;crx.pluspages=crx.pluspages||{};crx.pluspages=crx.pluspages;crx.notifications.Vb=1E4;crx.notifications.xb="SAPISID";crx.notifications.yb=".google.com";crx.notifications.R=!1;crx.notifications.Ub=["jgoepmocgafhnchmokaimcmlojpnlkhp","ljlimfijliceffddnmjecdgaihgocjfb","cpembckmhnjipbgbnfiocbgnkpjdokdd"];crx.notifications.Tb=["dlppkpafhbajpcmmoheippocdidnckmm","oelnpeknnoppmfhhhidlahkkacchafkm","hmglfmpefabcafaimbpldpambdfomanl"];crx.notifications.e={LOADING:0,ca:1,da:2,Sa:3};
crx.notifications.m=function(){var a=chrome.extension.getBackgroundPage();a&&a.window.controller||crx.A("Cannot access controller object for the background page.");return a.window.controller};window.crx=window.crx||{};window.crx.notifications=window.crx.notifications||{};window.crx.notifications.ENABLE_PLUSPAGES=crx.notifications.R;crx.notifications.b=function(a){this.la={};this.S={};this.l=this.r=!1;this.d=null;this.ia=a};crx.notifications.b.f=null;crx.notifications.b.create=function(a){crx.notifications.b.f&&crx.A("Trying to create a second Loader.");crx.notifications.b.f=new crx.notifications.b(!!a);return crx.notifications.b.f};crx.notifications.b.prototype.init=function(){this.load();var a=this;setTimeout(function(){a.r=!0;k(a)},0)};crx.notifications.b.Va="https://apis.google.com/js/plusone.js";crx.notifications.b.Ua="https://apis.google.com/js/plusone.js?onload=onPlusOneLoaded_&googleapis=1";
function l(){crx.notifications.b.f||crx.A("Error: PlusOne API loaded but no loader created.");crx.notifications.b.f.l=!0;k(crx.notifications.b.f)}var k=function(a){a.r&&a.l&&a.ja(a.la)};
crx.notifications.b.prototype.load=function(){if(this.l)k(this);else{this.d&&this.d.parentNode&&(this.d.parentNode.removeChild(this.d),this.d=null);this.d=document.createElement("script");this.d.type="text/javascript";this.d.async=!0;this.d.src=this.ia?crx.notifications.b.Va:crx.notifications.b.Ua;this.d.onerror=crx.bind(this.ja,this,this.S);this.d.innerText="{lang: navigator.language}";this.ia&&this.d.addEventListener("load",l,!1);var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(this.d,
a)}};var m=function(a,b,d,e){a.r&&a.l?d():(a.la[b]=d,e?a.S[b]=e:delete a.S[b])};crx.notifications.b.prototype.ja=function(a){for(var b in a){var d=a[b];d&&"function"==typeof d&&d();delete a[b]}};window.onPlusOneLoaded_=l;crx.notifications.ea="gpnext";crx.notifications.Ia="https://plus.google.com/u/0/_/notifications/frame";crx.notifications.Ta="https://www.google.com/accounts/ServiceLogin?service=oz";crx.notifications.Iframe=function(a,b,d,e,f,g){this.a=null;this.Ra=e;this.Qa=f;this.O=g;this.g=a;this.t=document.getElementById(a);this.s=this.u=null;this.h=b;this.D=d};crx.notifications.Iframe.fa="iframe-style";crx.notifications.Iframe.Ja=1E4;crx.notifications.Iframe.prototype.init=function(){crx.i18n.Z();this.t=document.getElementById(this.g)};
var n=function(a,b,d){return{onOpen:function(b){return b.openInto(a.g)},onReady:function(e){if(b.onReady)b.onReady(e);d&&crx.notifications.Iframe.H(e,"onShowNotificationsOnly",{maxWidgetHeight:a.D.ma,isExtension:!0})},onClose:function(a){if(b.onClose)b.onClose(a);a.remove()}}};crx.notifications.Iframe.H=function(a,b,d){a[b]&&"function"==typeof a[b]?a[b].apply(window,Array.prototype.slice.call(arguments,2)):crx.A("Method "+b+" not defined on iframe.")};
crx.notifications.Iframe.prototype.Q=function(a,b,d){d||(d={});p(this);this.s=setTimeout(crx.bind(this.Ka,this),crx.notifications.Iframe.Ja);if(this.h.r&&this.h.l){iframes.setHandler(crx.notifications.Iframe.fa,n(this,a,b));a={setNotificationWidgetSize:crx.bind(this.Oa,this),setNotificationText:crx.bind(this.Na,this),postShareMessage:crx.bind(crx.ga,this,"postShareMessage"),openSharebox:crx.bind(crx.ga,this,"openSharebox"),onError:crx.bind(this.La,this),hideNotificationWidget:window.close,onInfo:crx.bind(this.Ma,
this)};b=crx.notifications.Ia+"#pid="+crx.notifications.ea;for(var e in d)b+="&"+e+"="+d[e];this.a=iframes.open(b,{style:crx.notifications.Iframe.fa},{sourceid:crx.notifications.ea,origin:window.location.origin,hl:window.navigator.language},a,function(){})}else m(this.h,"iframe",crx.bind(this.Q,this,a,b,d),crx.bind(this.O,this))};crx.notifications.Iframe.prototype.Ka=function(){this.s=null;crx.B("Timeout during PlusOne API or iframe loading.");this.O()};
crx.notifications.Iframe.prototype.Oa=function(a,b){q(this,a,b)};crx.notifications.Iframe.prototype.Na=function(a,b,d,e){p(this);d=parseInt(a,10);b||(b=9>=d?a:"9+");this.Ra(d,b,e&&e.hasUnread?!0:!1)};crx.notifications.Iframe.prototype.La=function(a,b){crx.B("Error numer "+a+": "+b);this.O()};crx.notifications.Iframe.prototype.Ma=function(a){p(this);3==a&&this.Qa()};var p=function(a){a.s&&(clearTimeout(a.s),a.s=null)};crx.notifications.Iframe.prototype.load=function(a,b){this.Q(a,!1,b)};
crx.notifications.Iframe.prototype.open=function(a,b){this.Q(a,!0,b)};crx.notifications.Iframe.prototype.close=function(){crx.notifications.Iframe.H(this.a,"onHide")};var q=function(a,b,d){a.u&&(clearTimeout(a.u),a.u=null);a.u=setTimeout(function(){a.u=null;a.t.style.width=b;a.t.style.height=d},100)};crx.notifications.Iframe.prototype.setIsPolling=function(a){this.a&&this.a.onActive&&(a?crx.notifications.Iframe.H(this.a,"onActive"):crx.notifications.Iframe.H(this.a,"onIdle"))};
var r=function(a,b){a.t.style.display=b?"block":"none"};crx.pluspages.Pa=function(){this.ma=580};crx.pluspages.e={pa:0,Za:1};crx.pluspages.Qb={Yb:0,$b:1,CLOSED:2};crx.pluspages.Wb={Zb:0,Ob:1,Pb:2};crx.pluspages.xb="SAPISID";crx.pluspages.yb=".google.com";crx.pluspages.qa={permissions:[],origins:["http://*/*","https://www.googleapis.com/*","https://www.clients6.google.com/*"]};crx.pluspages.Ca="plus_follow_state";crx.pluspages.Ba="had_pre_plusfollow_build";crx.pluspages.rb="plus_follow_offered";crx.pluspages.Ya="chrome-ext-brand-badge";crx.pluspages.jb=["author","publisher","me"];
crx.pluspages.kb=/^https?:\/\/plus\.google\.com/;crx.pluspages.za=/\/\/[^\/]*\/[^\?]*([0-9]{21})/;crx.pluspages.nb=/(Chrom(e|ium))\/([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/;crx.pluspages.eb=[18,0,1025,162];crx.pluspages.cb=[19,0,1084,35];
crx.pluspages.Ac=function(){var a=null;(a=crx.pluspages.N(document.getElementsByTagName("link")))||(a=crx.pluspages.N(document.getElementsByTagName("g:plus")));a||(a=crx.pluspages.N(document.getElementsByClassName("g-plus")));a||(a=crx.pluspages.N(document.getElementsByTagName("a")));return a};crx.pluspages.N=function(a){for(var b=0;b<a.length;b++){var d=crx.pluspages.Cb(a[b]);if(d)return d}return null};
crx.pluspages.vb=function(a){var b,d=[];"G:PLUS"==a.tagName?(b=crx.pluspages.aa(a.getAttribute("href")),d.push("publisher")):"DIV"==a.tagName?(b=crx.pluspages.aa(a.getAttribute("data-href")),d.push("publisher")):b=crx.pluspages.aa(a.href);if(b.valid)for(a.rel&&(d=d.concat(a.rel.split(" "))),b.$&&(d=d.concat(b.$)),a=0;a<d.length;a++)if(0<=crx.pluspages.jb.indexOf(d[a]))return b.source};crx.pluspages.Cb=function(a){if(a=crx.pluspages.vb(a))return crx.pluspages.ub(a)};
crx.pluspages.ub=function(a){if(a=crx.pluspages.za.exec(a))return a[1]};crx.pluspages.aa=function(a){var b={source:a,valid:!1,$:[]};if(!crx.pluspages.kb.exec(a))return b;a=a.split("?",2);if(!crx.pluspages.za.exec(a[0]))return b;b.valid=!0;a[1]&&(a=("&"+a[1]).match(/&rel=([^&]*)/))&&(b.$=decodeURIComponent(a[1]).split(" "));return b};crx.pluspages.ra=function(){var a=chrome.extension.getBackgroundPage();a&&a.window.tabManager||crx.A("Cannot access tab manager object for the background page.");return a.window.tabManager};
crx.pluspages.Gc=function(){window.localStorage.removeItem(crx.pluspages.Ba);window.localStorage.setItem(crx.pluspages.rb,"true");chrome.extension.sendRequest({msg:"plusFollowPromoClick"})};crx.pluspages.Gb=function(){chrome.tabs.create({url:chrome.extension.getURL("followpromo.html")});chrome.extension.sendRequest({msg:"plusFollowPromoPageOpened"})};
crx.pluspages.Hc=function(a){chrome.permissions.request(crx.pluspages.qa,function(b){b?(crx.pluspages.V(crx.pluspages.e.Za),crx.pluspages.ra().init(),chrome.extension.sendRequest({msg:"plusFollowActivated"})):crx.pluspages.V(crx.pluspages.e.pa);a(b)})};crx.pluspages.fc=function(){crx.pluspages.V(crx.pluspages.e.pa);crx.pluspages.ra().cleanup();chrome.permissions.remove(crx.pluspages.qa,function(){})};crx.pluspages.xc=function(){return crx.pluspages.qb()&&crx.notifications.R};
crx.pluspages.getState=function(){return window.localStorage.getItem(crx.pluspages.Ca)};crx.pluspages.V=function(a){window.localStorage.setItem(crx.pluspages.Ca,a)};crx.pluspages.fb=function(){var a=crx.pluspages.nb.exec(window.navigator.userAgent);if(a&&3<a.length)return a[3];crx.B("Chrome version extraction failed");return""};crx.pluspages.wa=function(a,b){for(var d=0;d<a.length;d++){if(a[d]>b[d])return 1;if(a[d]<b[d])return-1}return 0};
crx.pluspages.qb=function(){var a=crx.pluspages.fb().split("."),b=crx.pluspages.eb,d=crx.pluspages.cb;if(4>a.length)return crx.B("Chrome version unknown, disabling +Follow"),!1;for(var e=[],f=0;f<a.length;f++)e.push(parseInt(a[f],10));return 0<=crx.pluspages.wa(a,b)&&0>=crx.pluspages.wa(a,d)?!1:!0};window.crx=window.crx||{};window.crx.pluspages=window.crx.pluspages||{};window.crx.pluspages.AUTO_UPDATE=crx.pluspages.Ba;window.crx.pluspages.onPopupPromoClicked=crx.pluspages.Gb;var s=s||{};s.global=this;s.Y=function(a,b,d){a=a.split(".");d=d||s.global;a[0]in d||!d.execScript||d.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};s.ec=function(a,b){s.Y(a,b)};s.X=!0;s.Xb="en";s.zb=!0;s.Bc=function(a){s.Y(a)};s.Fc=function(a){if(!s.X)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
s.lc=function(a){a=a.split(".");for(var b=s.global,d;d=a.shift();)if(s.Eb(b[d]))b=b[d];else return null;return b};s.oc=function(a,b){var d=b||s.global,e;for(e in a)d[e]=a[e]};s.bc=function(a,b,d){if(s.sa){var e;a=a.replace(/\\/g,"/");for(var f=s.p,g=0;e=b[g];g++)f.v[e]=a,a in f.W||(f.W[a]={}),f.W[a][e]=!0;for(e=0;b=d[e];e++)a in f.w||(f.w[a]={}),f.w[a][b]=!0}};s.Ic=!1;s.Sb=!0;s.Dc=function(){};s.F="";s.zc=function(){};s.pc=function(a){return a};
s.ac=function(){throw Error("unimplemented abstract method");};s.cc=function(a){a.Mb=function(){if(a.f)return a.f;s.X&&(s.va[s.va.length]=a);return a.f=new a}};s.va=[];s.sa=!1;
s.sa&&(s.Wa={},s.p={W:{},v:{},w:{},oa:{},G:{}},s.xa=function(){var a=s.global.document;return"undefined"!=typeof a&&"write"in a},s.Bb=function(){if(s.global.ib)s.F=s.global.ib;else if(s.xa())for(var a=s.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var d=a[b].src,e=d.lastIndexOf("?"),e=-1==e?d.length:e;if("base.js"==d.substr(e-7,7)){s.F=d.substr(0,e-7);break}}},s.na=function(a){var b=s.global.Nb||s.gb;!s.p.G[a]&&b(a)&&(s.p.G[a]=!0)},s.gb=function(a){if(s.xa()){var b=s.global.document;
if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+a+'">\x3c/script>');return!0}return!1},s.Jc=function(){function a(f){if(!(f in e.G)){if(!(f in e.oa)&&(e.oa[f]=!0,f in e.w))for(var h in e.w[f])if(!s.Kb(h))if(h in e.v)a(e.v[h]);else throw Error("Undefined nameToPath for "+h);f in d||(d[f]=!0,b.push(f))}}var b=[],d={},e=s.p,f;for(f in s.Wa)e.G[f]||a(f);for(f=0;f<b.length;f++)if(b[f])s.na(s.F+
b[f]);else throw Error("Undefined script input");},s.mc=function(a){return a in s.p.v?s.p.v[a]:null},s.Bb(),s.global.Rb||s.na(s.F+"deps.js"));
s.J=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};s.tc=function(a){return void 0!==a};s.vc=function(a){return null===a};s.Eb=function(a){return null!=a};s.isArray=function(a){return"array"==s.J(a)};s.qc=function(a){var b=s.J(a);return"array"==b||"object"==b&&"number"==typeof a.length};s.sc=function(a){return s.Fb(a)&&"function"==typeof a.getFullYear};s.yc=function(a){return"string"==typeof a};s.rc=function(a){return"boolean"==typeof a};s.wc=function(a){return"number"==typeof a};
s.uc=function(a){return"function"==s.J(a)};s.Fb=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};s.Db=function(a){return a[s.L]||(a[s.L]=++s.ob)};s.Ib=function(a){"removeAttribute"in a&&a.removeAttribute(s.L);try{delete a[s.L]}catch(b){}};s.L="closure_uid_"+(1E9*Math.random()>>>0);s.ob=0;s.ic=s.Db;s.Cc=s.Ib;s.mb=function(a){var b=s.J(a);if("object"==b||"array"==b){if(a.lb)return a.lb();var b="array"==b?[]:{},d;for(d in a)b[d]=s.mb(a[d]);return b}return a};
s.tb=function(a,b,d){return a.call.apply(a.bind,arguments)};s.sb=function(a,b,d){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}};s.bind=function(a,b,d){s.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?s.tb:s.sb;return s.bind.apply(null,arguments)};
s.Hb=function(a,b){var d=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,d);return a.apply(this,b)}};s.Ea=function(a,b){for(var d in b)a[d]=b[d]};s.now=s.zb&&Date.now||function(){return+new Date};
s.nc=function(a){if(s.global.execScript)s.global.execScript(a,"JavaScript");else if(s.global.eval)if(null==s.M&&(s.global.eval("var _et_ = 1;"),"undefined"!=typeof s.global._et_?(delete s.global._et_,s.M=!0):s.M=!1),s.M)s.global.eval(a);else{var b=s.global.document,d=b.createElement("script");d.type="text/javascript";d.defer=!1;d.appendChild(b.createTextNode(a));b.body.appendChild(d);b.body.removeChild(d)}else throw Error("goog.globalEval not available");};s.M=null;
s.hc=function(a,b){var d=function(a){return s.Aa[a]||a},e=function(a){a=a.split("-");for(var b=[],e=0;e<a.length;e++)b.push(d(a[e]));return b.join("-")},e=s.Aa?"BY_WHOLE"==s.pb?d:e:function(a){return a};return b?a+"-"+e(b):e(a)};s.Ec=function(a,b){s.Aa=a;s.pb=b};s.jc=function(a,b){var d=b||{},e;for(e in d){var f=(""+d[e]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f)}return a};s.kc=function(a){return a};
s.Ab=function(){s.Y("crx.notifications.Popup.main",crx.notifications.c.ua,void 0)};s.gc=function(a,b,d){a[b]=d};s.Da=function(a,b){function d(){}d.prototype=b.prototype;a.K=b.prototype;a.prototype=new d;a.prototype.constructor=a};
s.dc=function(a,b,d){var e=arguments.callee.caller;if(s.X&&!e)throw Error("arguments.caller not defined.  goog.base() expects not to be running in strict mode. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(e.K)return e.K.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),g=!1,h=a.constructor;h;h=h.K&&h.K.constructor)if(h.prototype[b]===e)g=!0;else if(g)return h.prototype[b].apply(a,f);if(a[b]===e)return a.constructor.prototype[b].apply(a,
f);throw Error("goog.base called from a method of one name to a method of a different name");};s.scope=function(a){a.call(s.global)};s.wb=!0;
s.wb&&(Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var d=Array.prototype.slice.call(arguments,1);d.unshift(this,a);return s.bind.apply(null,d)}return s.bind(this,a)},Function.prototype.Hb=function(a){var b=Array.prototype.slice.call(arguments);b.unshift(this,null);return s.bind.apply(null,b)},Function.prototype.Da=function(a){s.Da(this,a)},Function.prototype.Ea=function(a){s.Ea(this.prototype,a)});crx.notifications.c=function(a,b,d,e,f){this.g=a;this.Ga=b;this.Fa=d;this.P=this.o=this.C=this.q=this.a=null;this.n=chrome.extension.connect({name:"popup"});this.i=null;var g=this;this.n.onMessage.addListener(function(a){"STATE_CHANGED"==a.content&&t(g)});a=crx.notifications.m();this.a=new crx.notifications.Iframe(this.g,e,f,crx.bind(this.Ha,this),crx.bind(a.switchToState,a,crx.notifications.e.da),crx.bind(a.switchToState,a,crx.notifications.e.ca))};
var u=function(a){a.o=document.createElement("div");a.o.appendChild(document.createTextNode(chrome.i18n.getMessage("error_message")));a.P=document.createElement("div");a.o.appendChild(a.P);a.o.appendChild(document.createElement("br"));var b=document.createElement("a");b.addEventListener("click",function(){crx.notifications.m().switchToState(crx.notifications.e.LOADING);chrome.extension.sendRequest({msg:"retryNowClicked"})},!1);b.appendChild(document.createTextNode(chrome.i18n.getMessage("retry_now")));
a.o.appendChild(b)};crx.notifications.c.prototype.Ha=function(a,b){this.q.style.display="none";this.C.style.display="none";"none"==this.a.t.style.display&&r(this.a,!0);this.n&&this.n.postMessage({name:"newCountPolled",newCount:a,newDisplayText:b})};
var t=function(a){var b=crx.notifications.m().getState();a.i&&clearInterval(a.i);switch(b){case crx.notifications.e.Sa:v(a);a.a.open({onReady:function(){crx.notifications.m().setIsPolling(!1)},onClose:crx.bind(a.ba,a)});break;case crx.notifications.e.da:w(a);chrome.tabs.create({url:crx.notifications.Ta});break;case crx.notifications.e.LOADING:v(a);break;case crx.notifications.e.ca:x(a)}},x=function(a){a.i&&clearInterval(a.i);a.ya()||(a.i=setInterval(crx.bind(a.ya,a),500))};
crx.notifications.c.prototype.ya=function(){var a=crx.notifications.m().getTimeUntilNextReloadMs(),a=Math.round(a/1E3);crx.notifications.c.ha(this.P,document.createTextNode(chrome.i18n.getMessage("retrying_in",[a])));y(this,this.o);(a=0==a)&&this.i&&clearInterval(this.i);return a};var w=function(a){var b=document.createTextNode(chrome.i18n.getMessage("sign_in_message"));y(a,b)},y=function(a,b){a.a&&r(a.a,!1);a.C.style.display="none";a.q.style.display="block";crx.notifications.c.ha(a.q,b)};
crx.notifications.c.ha=function(a,b){if(1!=a.childNodes.length||a.firstChild!=b){for(;0<a.childNodes.length;)a.removeChild(a.firstChild);a.appendChild(b)}};var v=function(a){a.a&&r(a.a,!1);a.C.style.display="block";a.q.style.display="none"};crx.notifications.c.prototype.ba=function(){crx.notifications.m().setIsPolling(!0);this.a&&this.a.close()};
crx.notifications.c.ua=function(){var a=crx.notifications.b.create(!1),b=new crx.pluspages.Pa,d=new crx.notifications.c("notifications-target","message-div","loading-div",a,b);crx.notifications.R&&new crx.pluspages.c("gpf-badgeContainer",a,b);document.addEventListener("DOMContentLoaded",function(){a.init();d.q=document.getElementById(d.Ga);d.C=document.getElementById(d.Fa);u(d);d.a.init();window.addEventListener("unload",crx.bind(d.ba,d),!1);t(d)},!1)};s.Ab();crx.pluspages.c=function(a,b,d){this.g=a;this.h=b;this.D=d;this.T=null;this.j=new crx.U};crx.pluspages.c.prototype.init=function(){this.T=chrome.extension.connect({name:"plus_follow_popup"});this.j.register(this.T.onMessage,crx.bind(this.hb,this))};crx.pluspages.c.prototype.hb=function(a){if(a.disconnect){document.getElementById(this.g).style.display="none";a=this.j;for(var b in a.j)a.j[b].Xa(),delete a.j[b];this.T=null}else a.profileData&&a.profileData.url&&(this.D.Lb=70,this.D.ma=530,this.ka(a.profileData.url))};
crx.pluspages.c.prototype.ka=function(a){if(this.h.r&&this.h.l){var b=document.createElement("div");b.innerHTML='<div style=" height: 56px; width: 430px;padding:5px;"> <g:plus href ="'+a+'" width="430" height="69" theme="light" actionsource="'+crx.pluspages.Ya+'"></g:plus></div>';document.getElementById(this.g).appendChild(b);window.gapi.plus.go();document.getElementById(this.g).style.display="block"}else m(this.h,"pluspage-popup",crx.bind(this.ka,this,a))};crx.notifications.c.ua();
