"use strict";(function(){var f=devhd.pkg("pages");var b=f.BasePage.prototype;var e=f.createClass("SourcesPage",f.BasePage);var l=devhd.log.get("page.sources");var g=devhd.i18n.L;e.initialize=function(o){b.initialize.call(this);this.guid=o};e.service=function(p,o){this.pageInfo=p;this.width=o.width;this.initBase(o);this.startRenderHTML()};e.destroy=function(){this.destroyBase()
};e.allowsSideArea=function(){return false};e.allowsPageHeader=function(){return true};e.showCustomizer=function(o){this.showListCustomizer(o.target)};e.startRenderHTML=function(){this.feedly.clearNbrPages();this.feedly.pushContext({uri:"sources",pageNumber:this.pageInfo.pageNumber,title:"sources",level:1,category:"#sources"});k.call(this)};function k(){this.unbindAll();
if(this.pageModel!=null){this.signs.setMessage(g(97))}var o=this;n.call(this,function(p){i.call(o,p)})}function n(q){var o={favoritesOnly:this.getPreference("favoritesOnlyFilter")=="on",term:this.pageInfo.term};var p=this;this.reader.askSourcesModel(o,q)}function i(o){this.pageModel=o;this.feedly.setPageTitle(templates.page.sources.title(this.pageModel));
this.pageElem.innerHTML=templates.page.sources.layout(this.pageModel,this.width,this.pageInfo.term,this.home);var p=new devhd.behaviors.Dragable();p.setDndHandler({$this:this,$fn:e.dndHandler});this.bind(this.pageElem,p)}function h(o){this.signs.setNextAutoHideDelay(10000);this.signs.setMessage(templates.unoMomento());var p=o.origValue;var q=o.value;
if(p==null){l.warn(129,"category rename, old category is null ? ");o.undo();return}l.trace(133,"new-category name : ",q," changed category name ",p);j.call(this,p,q)}e.dndHandler=function(q,o){if(q=="dragStart"){var p=devhd.utils.HTMLUtils.findParentElementByTagAndAttribute(o.src,"*","data-category","*");o.data={};o.data.feedid=o.src.getAttribute("data-feedId");
o.data.oldCat=p?p.getAttribute("data-category"):null;if(o.data.oldCat==null){o.cancel=true;return}o.dragable.innerHTML=devhd.utils.HTMLUtils.outerHTML(o.src);o.dragableSet=true}else{if(q=="dragOver"){o.data.newCat=o.target.getAttribute("data-category")}else{if(q=="dragOut"){delete o.data.newCat}else{if(q=="dragDrop"){d.call(this,o)}else{if(q=="dragEnd"){}}}}}};
function d(o){if(o.data.feedid){if(o.data.newCat=="##tag##"){this.dialog.show(templates.forms.newCategory(""),550);var p=this;this.bind("create","click",function(){var q=devhd.str.trim(p.element("categoryLabel").value);p.dialog.hide();a.call(p,[o.data.feedid],o.data.oldCat,q)});this.bind("cancel","click",function(){p.dialog.hide()})}else{if(o.data.newCat){if(o.data.newCat!=o.data.oldCat){a.call(this,[o.data.feedid],o.data.oldCat,o.data.newCat)
}else{this.signs.setNextAutoHideDelay(2000);this.signs.setMessage(templates.page.sources.sameCategory(o.data.oldCat));l.trace(217,"old and new category are the same ... skipping")}}else{l.error(222,"new category is not set, cannot perform operation")}}}else{if(o.data.newCat){if(o.data.newCat==o.data.oldCat){this.signs.setNextAutoHideDelay(2000);this.signs.setMessage(templates.page.sources.sameCategory(o.data.oldCat));
l.trace(233,"old and new category are the same ... skipping")}else{l.trace(237,"merging ",o.data.oldCat," with ",o.data.newCat);j.call(this,o.data.oldCat,o.data.newCat)}}else{l.error(244,"new category is not set, cannot merge")}}}e.removeCategory=function(o){var p=false;if(p==true){this.signs.setMessage(templates.page.base.confirmUnsubscribeCategory(o,this.home),0.8,true,this);
this.signs.setNextAutoHideDelay(45*1000)}else{this.doRemoveCategory(o)}};e.doRemoveCategory=function(o){this.signs.hide();var p={categoryLabel:o};var q=this;this.reader.askSubscriptions(p,function(r){if(r==null||r.length==0){k.call(q);return}q.processing=true;devhd.utils.FlowUtils.forEach({},r,function(u,s,w,t,v){if(q.isDestroyed()){return}devhd.fn.callback(v,u.id);
if(u.listCategoryLabels().length>1){m.call(q,u.id,o,null,function(){devhd.fn.callback(w)},t)}else{q.reader.askRemoveSubscription(u.id,function(){devhd.fn.callback(w)},t)}},{onStart:function(){q.progressDialog.show(g(98),r.length+1)},onSuccess:function(){q.processing=false;q.progressDialog.hide();k.call(q)},onError:function(s){q.processing=false;q.progressDialog.hide();
q.signs.setMessage(g(g(93),s))},onProgress:function(s){q.progressDialog.reportProgress(s)}})})};e.renameCategory=function(o){this.dialog.show(templates.forms.editCategory(o),550);var p=this;this.bind("rename","click",function(){var q=p.element("categoryLabel").value;p.dialog.hide();j.call(p,o,q)});this.bind("cancel","click",function(){p.dialog.hide()
})};function j(o,q){var p={categoryLabel:o,searchTerm:null,nonEmptyOnly:false,favoriteOnly:this.getPreference("sourcesFavoritesOnlyFilter")=="on"};var r=this;this.reader.askSubscriptions(p,function(u){var s=[];for(var t=0;t<u.length;t++){s.push(u[t].id)}a.call(r,s,o,q)})}function a(o,p,q){this.processing=true;var r=this;devhd.utils.FlowUtils.forEach({},o,function(s,t,w,u,v){if(r.isDestroyed()){return
}devhd.fn.callback(v,s);m.call(r,s,p,q,function(){devhd.fn.callback(w)},u)},{onStart:function(){r.progressDialog.show("Re-organizing sources",o.length+1)},onSuccess:function(){r.processing=false;r.progressDialog.hide();k.call(r)},onError:function(s){r.processing=false;r.progressDialog.hide();r.signs.setMessage(g(g(93),s))},onProgress:function(s){r.progressDialog.reportProgress(s)
}})}function m(p,q,r,v,t){var s=this;var o=r;if(o){if(typeof o=="string"){o=[r]}}var u=q;if(u){if(typeof u=="string"){u=[u]}}this.reader.askUpdateSubscription(p,null,o,u,{},false,v,t)}e.onSubscriptionFavoriteStatusChanged=function(o,r){var q=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"feedIconSources","data-feedId":o});for(var p=0;p<q.length;
p++){q[p].style.opacity=r?1:0.1}};e.onSubscriptionRemoved=function(o,r){if(this.processing==true){return}var q=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"subscriptionSources","data-feedId":o});for(var p=0;p<q.length;p++){c.call(this,q[p])}};e.onSubscriptionUpdated=function(o){if(this.processing==true){return}k.call(this)};e.onSubscriptionUnreadCountChanged=function(p,o){};
e.onSubscriptionAddedToCategory=function(p,o,q){};e.onSubscriptionRemovedFromCategory=function(p,o,q){};function c(o){this.effects.fade(o,{delay:0.4,from:1,to:0,onComplete:function(p){devhd.utils.HTMLUtils.remove(p)}},"feedly")}})();