"use strict";(function(){var a=devhd.pkg("pages");var c=devhd.i18n.L;var b=devhd.log.get("page.my");a.MyPage=function(){};var f=a.MyPage.prototype=new a.BasePage();f.service=function(h,g){this.pageInfo=h;this.width=g.width;this.categoryLabel="#"+h.type;this.initBase(g);this.startRenderHTML()};f.destroy=function(){if(this.topArea!=null){this.topArea.destroy();
this.topArea=null}this.entryIndex=null;this.allIds=null;this.entries=null;this.summary=null;this.recs=null;this.c2e=null;this.destroyBase()};f.allowsSearch=function(){return true};f.getSearchScope=function(){return devhd.utils.IdUtils.formatId("category","global.all",this.home.getUserId())};f.startRenderHTML=function(){try{this._cancelAllVisualFinders();
this.entryIndex={};this.endOfList=null;this.state="loading";this.selectedEntryId=null;var g=this.hideReadArticlesFilter()?"read":null;this.feedly.pushContext({uri:this.pageInfo.uri,title:"digest",pageNumber:this.pageInfo.pageNumber,level:1,queryInfo:{flsId:this.categoryLabel,excludeLabel:g},category:this.categoryLabel});this.trackTime("pushed context");
this.feedly.clearNbrPages();this.feedly.setPageTitle(templates.page.my.title());this.trackTime("updated chrome");var h=this;this.reader.askSections({excludeEmpty:true},function(k){e.call(h,k)})}catch(i){var j=devhd.utils.ExceptionUtils.formatError("layout top area",i);this.pageElem.innerHTML=j}};function e(j){try{if(j.length==0){this.displayEmptyMessage();
return}this.pageElem.innerHTML=templates.page.my.layout(j,this.width,this.home);this.trackTime("initial layout");this.entries=[];this.c2e={};this.allIds=[];var g=this;this.reco.askStreamDigest({featured:this.getPreference("featuredArticles")=="yes"&&false},function(){if(g.isDestroyed()==true){return}for(var n=0;n<j.length;n++){var k=g.c2e[j[n].label];
if(k==null){continue}for(var m=0;m<k.length;m++){var l=k[m];g.entryIndex[l.getId()]=l;g.entries.push(l);g.allIds.push(l.getId())}}if(g.allIds.length==0){g.signs.setNextAutoHideDelay(7000);g.signs.setMessage("No Unread Articles. All Done!")}g.feedly.setPageTitle(templates.page.my.title(g.allIds.length))},function(k,l){},function(l){if(g.isDestroyed()==true){return
}for(var k=0;k<l.length;k++){d.call(g,l[k])}})}catch(h){var i=devhd.utils.ExceptionUtils.formatError("layout top area",h);this.pageElem.innerHTML=i}}function d(h){switch(h.label){case"#top":var t=this.element("topArea");if(t==null){this.pageElem.innerHTML="failed to lookup top area element";return}if(h.top40.length==0){this.element("main_#featured").style.display="none";
return}h.top40=this.pickFeaturedEntries(h.top40);this.topArea=new devhd.control.RecommendationAreaControl();this.topArea.setHome(that.home);this.topArea.setReader(that.reader);this.topArea.setFeatured(h.top40);this.topArea.setPage(that);this.topArea.setPart(t);this.topArea.display();for(var m=0;m<h.top40.length;m++){this.allIds.push(h.top40[m].getId());
this.entries.push(h.top40[m])}this.c2e["#featured"]=new Array().concat(h.top40);break;default:var o=this.element("main_section_"+h.label+"_entries");if(o==null){return}var r=h.top40;r=r.sort(function(j,i){return i.crawledTime-j.crawledTime});if(r.length==0){if(h.feedId!=null){this.element("main_section_"+h.feedId+"_holder").style.display="none"}else{this.element("main_section_"+h.label+"_holder").style.display="none"
}this.c2e[h.label]=[];return}var s=0;var q=0;var p=0;for(var m=0;m<r.length;m++){if(r[m].listContentVisuals().length==0){p++}if(r[m].metadata.u==6){q++}}if(q>0&&q>=r.length-1&&p<=1){s=6}var n=[];if(s==6){var l=[];for(var k=0;k<r.length&&n.length<6;k++){l.push({entry:r[k],type:s});n.push(r[k])}o.className=o.className+" u6EntryList";o.style.marginRight="-34px";
o.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true,clear:"both"},this.home);for(var k=0;k<r.length;k++){this.askFindVisual(r[k],"U"+s)}}else{var g=Math.ceil(r.length-3);if(g<4){g=4}var l=[];for(var k=0;k<r.length&&k<g;k++){l.push({entry:r[k],type:4});n.push(r[k])
}o.innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home);for(var k=0;k<r.length&&k<g;k++){this.askFindVisual(r[k],"U4")}l=[];for(var k=g;k<r.length;k++){l.push({entry:r[k],type:12});n.push(r[k])}if(l.length>0){this.element("main_section_"+h.label+"_saved").innerHTML=templates.page.base.parts(l,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home)
}}this.askAdjustEntries(r);this.c2e[h.label]=n}}f.markSectionAsRead=function(k){var h=[];var l=this.c2e[k];for(var g=0;g<l.length;g++){h.push(l[g].getId())}var j=this;this.reader.askMarkEntriesAsRead(h,function(){},function(i){j.signs.setMessage("Error:"+i)})};f.markPageAsRead=function(){this.signs.setMessage(c(91),100);var g=this;this.home.getDocument().defaultView.setTimeout(function(){g.reader.askMarkEntriesAsRead(g.allIds,function(){},function(h){g.signs.setMessage("Error:"+h)
})},15)};f.markAsRead=f.markPageAsRead;f.onSubscriptionMarkedAsRead=function(g){var h=this.element("main_section_"+g+"_holder");if(h!=null){this.effects.fade(h,{delay:1,from:1,to:0,onComplete:function(i){devhd.utils.HTMLUtils.remove(i)}},"feedly")}};f.onSubscriptionRemoved=function(g,i){if(i==true){return}var h=this.element("main_section_"+g+"_holder");
if(h!=null){this.effects.fade(h,{delay:1,from:1,to:0,onComplete:function(j){devhd.utils.HTMLUtils.remove(j)}},"feedly")}else{this.feedly.reloadPage()}};f.findNextEntryId=function(l){var k=false;if(this.selectedEntryId==null){k=true}for(var j=0;j<this.entries.length;j++){var h=this.entries[j].getId();if(k==true){var g=this.entries[j];if(g.jsonInfo.buried==true){continue
}if(l==true){if(g.isRead()==false){return h}else{continue}}else{return h}}if(h==this.selectedEntryId){k=true}}return null};f.findPreviousEntryId=function(l){var k=false;if(this.selectedEntryId==null){k=true}for(var j=this.entries.length-1;j>=0;j--){var h=this.entries[j].getId();if(k==true){var g=this.entries[j];if(g.jsonInfo.buried==true){continue}if(l==true){if(g.isRead()==false){return h
}else{continue}}else{return h}}if(h==this.selectedEntryId){k=true}}return null};f.onPreviousEntry=function(i,g){var h=this.findPreviousEntryId(i);if(h!=null){if(g==true){this.selectEntry(h,"toview")}else{this.inlineEntry(h,true,true)}}else{this.signs.setMessage(c(95))}};f.onNextEntry=function(i,g){var h=this.findNextEntryId(i);if(h!=null){if(g==true){this.selectEntry(h,"toview")
}else{this.inlineEntry(h,true,true)}}else{this.signs.setMessage(c(96))}}})();