"use strict";(function(){var a=devhd.pkg("pages");var d=devhd.i18n.L;var c=devhd.log.get("page.list");a.ListPage=function(){};var f=a.ListPage.prototype=new a.BasePage();f.service=function(j,i){this.pageInfo=j;this.width=i.width;this.feedId=devhd.utils.FeedIdUtils.create(j.key);this.category=this.pageInfo.label;this.condensed=this.getPreference("entryOverviewSize.desktop")==0;
this.searchTerm=this.pageInfo.searchTerm;this.loadTime=new Date().getTime();if(this.searchTerm!=null&&this.home.isProPlan()==false){this.feedly.redirect("pro/search");return}this.action=j.parameters.action;this.returnTo=j.parameters.returnTo;if(this.pageInfo.pageNumber<0){c.warn(43,"invalid page number: ",this.pageInfo.pageNumber,". Hint:",this.pageInfo.uri);
this.pageInfo.pageNumber=0}if(j.key==null||j.key==""){this.signs("Invalid request. No feed or category specified");return}var k=this;this.reader.askSubscription(this.feedId,function(m){if(k.isDestroyed()||k.feedly==null){return}k.subscription=m;if(k.category==null&&k.subscription!=null){var l=devhd.utils.ContextStackUtils.find(k.feedly.getContextStack(),"category");
if(l!=null){k.category=l}}k.dontSort=k.pageInfo.key.indexOf("state/com.google/broadcast")>-1||k.pageInfo.uri.indexOf("feedly.saved")>-1||k.pageInfo.uri=="saved"||k.getPreference("entryOverviewSize.desktop")==0;k.socialMix=k.pageInfo.key.indexOf("state/com.google/broadcast-")>-1;k.realtimeScrolling=true;k.initBase(i);k.startRenderHTML()})};f.destroy=function(){if(this.topArea!=null){this.topArea.destroy()
}this.destroyBase()};f.allowsSideArea=function(i){if(i.searchTerm!=null){return true}return i.preferences["entryOverviewSize.desktop"]!=0&&i.preferences["entryOverviewSize.desktop"]!=5};f.allowsSearch=function(){return true};f.getSearchScope=function(){return this.feedId};f.getNakedURI=function(){if(this.feedId.indexOf("global.all")>-1){return"latest"
}else{if(this.category!=null){return"category/"+this.category}else{return"subscription/"+this.feedId}}};f.isLayoutAware=function(){return true};f.markSectionAsRead=function(l){if(this.featured==null||this.featured.length==0){return}var k=[];for(var j=0;j<this.featured.length;j++){k.push(this.featured[j].getId())}this.reader.askMarkEntriesAsRead(k,function(){},function(i){that.signs.setMessage("Error:"+i)
})};f.startRenderHTML=function(){this._cancelAllVisualFinders();this.endOfList=null;this.state="loading";this.pageElem.innerHTML=templates.page.list.prelayout(this.home,this.searchTerm);var i=this;this.reader.askFeedInformation(this.feedId,function(j){if(i.isDestroyed()==true){return}i.onFeedInformationReady(j)},function(j){if(i.isDestroyed()==true){return
}i.feedly.setPageTitle("Feed not found");i.pageElem.innerHTML=templates.page.base.invalidFeed(j,i.feedId,i.home)})};f.showCustomizer=function(i){this.showListCustomizer(i.target)};f.bigMarkAsRead=function(){var i=this.element("bigMarkAsReadHandle");if(i==null){this.markAsRead();return}i.style.backgroundColor=feedlyTheme.ma_accent;i.style.opacity="0.7";
i.innerHTML="Processing...";var j={};j.lastReadEntryId=this.marker;var k=this;if(this.subscription!=null){this.markAllSubscriptionEntriesAsRead(this.subscription.id,false,j,function(){i.innerHTML="Marked as read";k.home.getDocument().defaultView.setTimeout(function(){k.feedly.jumpToNext()},1000)})}else{if(this.category!=null){this.markCategoryAsRead(this.category,{},true,function(){i.innerHTML="Marked as read";
k.home.getDocument().defaultView.setTimeout(function(){k.feedly.jumpToNext()},1500)})}}};f.markAsRead=function(i){var l=(i==null);var j={};if(i!=null&&isNaN(i)==false){j.asOf=i}else{j.lastReadEntryId=this.marker}this.popup.hide();var k=this;if(this.subscription!=null){this.markAllSubscriptionEntriesAsRead(this.subscription.id,false,j,function(){if(l){k.feedly.jumpToNext()
}else{k.feedly.reloadPage({forceRecreate:true})}})}else{if(this.category!=null){this.markCategoryAsRead(this.category,i,false,function(){if(l){k.feedly.jumpToNext()}else{k.feedly.reloadPage({forceRecreate:true})}})}}};f.askDecorateMetadata=function(){if(this.feedId==null||this.feedId.indexOf("feed/")!=0){return}var i=this;this.reader.askFeedMetadata(this.feedId,function(l){var m=templates.modules.about(l);
var j=devhd.utils.HTMLUtils.findElements(i.home.getDocument(),{className:"feedMetadata","data-feedId":i.feedId});for(var k=0;k<j.length;k++){j[k].innerHTML=m}})};f.markAsReadOneDay=function(){this.markAsRead((new Date().getTime()-devhd.utils.DurationUtils.DAYS(1)))};f.markAsReadOneWeek=function(){this.markAsRead((new Date().getTime()-devhd.utils.DurationUtils.DAYS(7)))
};var h=3;var e=3;f.onFeedInformationReady=function(i){try{if(this.isDestroyed()){return}this._cancelAllVisualFinders();this.endOfList=null;this.state="loading";this.selectedEntryId=null;this.feedInfo=i;this.feedly.clearNbrPages();if(i==null||i.state=="dead"){this.feedly.setPageTitle("Ooops!");this.pageElem.innerHTML=templates.page.list.notFound(i);
return}this.feedly.pushContext({uri:this.pageInfo.uri,title:this.feedInfo.title,pageNumber:this.pageInfo.pageNumber,level:this.feedInfo.level==1?1:2,queryInfo:{flsId:this.feedInfo.id,excludeLabel:this.hideReadArticlesFilter()?"read":null},category:(this.subscription!=null?this.subscription.getDefaultCategoryLabel():null)||this.category,feedId:this.pageInfo.type=="subscription"?this.pageInfo.key:null,searchTerm:this.searchTerm,website:this.feedInfo.website,subscriptions:this.subscription!=null?[this.subscription.id]:null});
this.feedly.setPageTitle(templates.page.list.title(this.feedInfo,{maxWidth:this.width-20,subscription:this.subscription,website:this.feedInfo.website,u:this.getPreference("entryOverviewSize.desktop"),type:this.pageInfo.type,searchTerm:this.searchTerm},this.home));this.pageElem.innerHTML=templates.page.list.layout(this.feedInfo,parseInt(this.getPreference("entryOverviewSize.desktop")),this.nbrColumns,this.width,this.pageInfo.uri=="saved"||(this.feedId.indexOf("feed/")==0&&this.subscription==null)?"notSubscribed":"",this.searchTerm);
this.entries=[];this.index={};this.nbrColumns=this.getPreference("entryOverviewSize.desktop")==5?3:1;this.splitBy=this.getPreference("entryOverviewSize.desktop")==6||this.getPreference("entryOverviewSize.desktop")==5?"monthly":"daily";if(this.getPreference("entryOverviewSize.desktop")==0){this.splitBy="none";this.analyzed=true}if(i.unreadCount==0&&this.hideReadArticlesFilter()!=false){this.element("noUpdatesMessage").style.display="block"
}this.lastSplit=null;this.batchId=-1;this.sectionId=-1;if(this.searchTerm==null&&this.getPreference("featuredArticles")=="yes"&&false&&this.pageInfo.pageNumber==0&&(this.getPreference("entryOverviewSize.desktop")=="4"||this.getPreference("entryOverviewSize.desktop")=="6")&&this.pageInfo.uri!="latest"&&this.category!="#latest"&&(i.unreadCount>7||i.unreadCount==0)&&this.feedInfo.id.indexOf("com.google/alerts")==-1&&this.oldestFirst()!=true){this.featuredLoading=true;
this.element("featuredArea").style.display="block";var j=this;if(this.isFeed()){this.reco.askFeaturedEntries(this.feedInfo.id,{unreadOnly:this.determineHideReadArticlesFilter(),n:3},function(l){if(j.isDestroyed()==true){return}l=j.pickFeaturedEntries(l);if(l.length>=h){g.call(j,l)}else{j.element("featuredArea").style.display="none";j.entries=[]}j.featuredLoading=false;
j.askMoreEntries()},function(m,l){if(j.isDestroyed()==true){return}j.onEntriesError(j.feedInfo.id,m,l);j.featuredLoading=false;j.askMoreEntries()},true)}else{this.reco.askFeaturedEntries(devhd.utils.TermUtils.formatTerm(this.category,this.home.getUserId(),"category"),{unreadOnly:this.determineHideReadArticlesFilter(),n:3},function(l){if(j.isDestroyed()==true){return
}l=j.pickFeaturedEntries(l);if(l.length>=e){g.call(j,l)}else{j.element("featuredArea").style.display="none";j.entries=[]}j.featuredLoading=false;j.askMoreEntries()})}}else{this.element("featuredArea").style.display="none";this.featuredLoading=false;this.askMoreEntries()}if(this.action=="subscribe"&&this.home.getUserId()!=null){this.feedly.askAddSubscription(this.feedInfo.id,this.feedInfo.title)
}this.askDecorateMetadata()}catch(k){$feedly(devhd.utils.ExceptionUtils.formatError("layout feed info",k))}};function g(l){var k=this;this.featured=l;this.topArea=new devhd.control.RecommendationAreaControl();this.topArea.setHome(k.home);this.topArea.setReader(k.reader);this.topArea.setFeatured(l);this.topArea.setPage(k);this.topArea.showSourceTitle(k.subscription==null);
this.topArea.setPart(k.element("headline"));this.topArea.display();for(var j=0;j<l.length;j++){this.index[l[j].getId()]=true;this.entries.push(l[j])}}f.askMoreEntries=function(){if(this.isDestroyed()){return}if(this.feedInfo==null){return}if(this.fullyLoaded===true){return}if(this.featuredLoading===true){return}if(this.entriesLoading===true){return}this.batchId++;
this.entriesLoading=true;this.element("loadingEntries").style.display="block";var j=this.condensed?40:20;if(this.searchTerm!=null){j=10}var i=this;if(this.continuation==null&&this.searchTerm!=null){this.searchDots=3;this.searchMessageEnhanceTimer=this.home.getDocument().defaultView.setInterval(function(){var l="Searching";i.searchDots++;var m=i.searchDots;
if(i.searchDots>7){m=m-4;l="Searching archive"}for(var k=0;k<m;k++){l+="."}if(i.searchDots>12){i.element("loadingEntries").innerHTML="Sorry. This search is taking too long. Something must have gone wrong :-("}else{i.element("loadingEntries").innerHTML=templates.page.list.enhancedLoadingMessage(l)}},3000)}this.reader.askMoreEntries(this.feedInfo.id,{xt:this.determineHideReadArticlesFilter()?"read":null,r:this.oldestFirst()?"o":null,searchTerm:this.searchTerm},j,this.continuation,function(o,m,q,l){if(i.oldestFirst()!=true&&i.marker==null&&o.length>0){i.marker=o[0].getId()
}try{if(i.searchMessageEnhanceTimer!=null){i.home.getDocument().defaultView.clearInterval(i.searchMessageEnhanceTimer);i.searchMessageEnhanceTimer=null}}catch(s){}try{if(i.perfed!=true&&q!=null&&i.continuation==null){var k=devhd.utils.HTMLUtils.findElements(i.home.getDocument(),{className:"performance"});for(var n=0;n<k.length;n++){if(l!=null){k[n].innerHTML=" <span title='CPU time:"+l+"ms'>(served in "+q+"ms)</span>"
}else{k[n].innerHTML=" <span>(served in "+q+"ms)</span>"}}}}catch(s){$feedly("[list] failed to layer in performance information:"+q)}try{i.continuation=m;i.entriesLoading=false;i.fullyLoaded=m==null;if(i.isDestroyed()==true){return}var p=o.length==0&&this.batchId==1;try{i.onEntriesReady(o)}catch(r){$feedly("[list] failed to add entries because:"+r.name+" -- "+r.message)
}if(i.fullyLoaded){if(i.getPreference("giantMarkAsRead")=="yes"&&(i.subscription!=null||i.category!=null)&&p==false){i.element("aboutArea").innerHTML=templates.page.list.layoutMarkAsRead(i.subscription!=null);i.element("aboutArea").style.display="block"}else{i.element("fullyLoaded").style.display="block"}i.element("feedlyPart0").style.minHeight=(devhd.utils.HTMLUtils.getClientHeight(i.home.getDocument())-236)+"px"
}i.element("loadingEntries").style.display="none"}catch(r){i.element("loadingEntries").innerHTML="Failed to render entries. Bug:"+r.name+" -- "+r.message;i.element("loadingEntries").style.display="block"}},function(l,k){if(l==400&&this.searchTerm!=null){i.element("loadingEntries").innerHTML="Search failed. Invalid search term.";i.element("loadingEntries").style.display="block";
return}else{$feedly("[list] ask more entries failed:"+l+" -- "+k);i.entriesLoading=false;i.onEntriesError(l,k)}},this.pageInfo.uri=="saved")};f.isFeed=function(){return this.feedInfo.id!=null&&((this.feedInfo.id.indexOf("feed/")==0)||(this.feedInfo.id.indexOf("state/com.google/broadcast")>-1))};f.determineHideReadArticlesFilter=function(){if(this.pageInfo.type=="tag"){return false
}if(this.pageInfo.type=="saved"){return false}if(this.isFeed()&&(this.subscription==null||this.subscription.unreadCount==0)){return false}if(this.feedInfo!=null&&this.feedInfo.unreadCount==0){return false}if(this.hideReadArticlesFilter()==false){return false}return true};f.onPageScrollChanged=function(l,k){var i=this.home.getDocument().body;if(l+i.clientHeight>i.scrollHeight-700){this.askMoreEntries()
}if(k&&this.getPreference("autoSelectOnScroll")=="yes"&&parseInt(this.getPreference("entryOverviewSize.desktop"))!=6&&parseInt(this.getPreference("entryOverviewSize.desktop"))!=8&&this.inlinedEntryId==null){var j=this.findScrollFocus(l);if(j!=null){this.selectEntry(j,false)}}if(k&&this.getPreference("autoSelectOnScroll")=="inlined-only"&&parseInt(this.getPreference("entryOverviewSize.desktop"))==100){var j=this.findScrollFocus(l);
if(j!=null){this.selectEntry(j,false)}}};f.findScrollFocus=function(k){if(this.entries==null||this.entries.length==0){return null}var l=k+100;for(var i=0;i<this.entries.length;i++){var m=this.element(this.entries[i].getId()+"_main");if(m==null){continue}if(m.offsetTop<l&&m.offsetTop+m.clientHeight>l){return this.entries[i].getId()}}return null};f.onEntriesReady=function(q){try{if(this.isDestroyed()){return
}if(this.dontSort==false&&false){var s=this;q=q.sort(function(j,i){if(s.oldestFirst()){return j.crawledTime-i.crawledTime}else{return i.crawledTime-j.crawledTime}})}try{if(this.analyzed==null){this.analyzed=true;if(q.length>0){var k=new Date().getTime();var r=0;var t=0;for(var o=0;o<q.length;o++){if(q[o].metadata.skipVisual==true){r++}if(q[o].getAge()<24){t++
}}if(t>8){this.splitBy="daily"}if(r/q.length>0.8){this.element("mainArea").className=this.element("mainArea").className+" textOptimized"}}}if(this.feedInfo.label!=true&&this.websiteLinkOK!=true&&q.length>0){var l=this.element("main_"+this.feedInfo.id+"_title");if(l!=null){l.setAttribute("href",q[0].getSourceAlternateLink());l.removeAttribute("data-uri")
}this.websiteLinkOK=true}}catch(u){$feedly("[error] failed to refine link because:"+u.name+" -- "+u.exception)}var m=this.getPreference("entryOverviewSize.desktop");var p=0;for(var n=0;n<q.length;n++){if(this.index[q[n].getId()]!=null){continue}this.appendEntry(q[n],m);p++}if(q.length==0&&this.entries.length==0){this.element("emptyListMessage").style.display="block"
}}catch(u){this.element("loadingEntries").innerHTML="Oops. Run into a piece of content we failed to render:"+u.name+" -- "+u.message;this.element("loadingEntries").style.display="block"}};f.onEntriesError=function(k,j){var i=this.element("loadingEntries");if(i!=null){if(this.searchTerm!=null){i.innerHTML="Sorry. Search request failed or timed out:"+k+" -- "+j
}else{i.innerHTML="Sorry. Something went wrong:"+k+" --"+j}}else{if(this.searchTerm!=null){this.signs.setMessage("Search request failed or timed out:"+k)}else{this.signs.setMessage("Sorry. Server error:"+k)}}};f.onEndOfListDetected=function(){};f.appendSection=function(j){this.sectionId++;devhd.utils.HTMLUtils.append(this.element("timeline"),templates.page.list.layoutSection(this.sectionId,this.nbrColumns,j));
this.columns=[];for(var k=0;k<this.nbrColumns;k++){this.columns.push(this.element("section"+this.sectionId+"_column"+k))}this.nextColumnId=0};function b(i,j){if(this.pageInfo.preferences["entryOverviewSize.desktop"]==0){return"none"}else{if(this.nbrColumns>2||this.pageInfo.preferences["entryOverviewSize.desktop"]==6){return"feedly"}else{var k=i.getCrawledDate();
switch(j){case"monthly":return k.getFullYear()+"-"+k.getMonth();default:return k.getFullYear()+"-"+k.getMonth()+"-"+k.getDate()}}}}f.appendEntry=function(i,l){try{var m=b.call(this,i,this.splitBy);if(this.lastSplit!=m){this.lastSplit=m;this.appendSection(templates.page.list[this.splitBy+"Separator"](i))}var j=this.columns[this.nextColumnId];devhd.utils.HTMLUtils.append(j,templates.page.base.parts([{entry:i,type:l}],this.width,{feedInfo:this.feedInfo,includeDateSeparator:false,includeCategoryLabel:false,includeSourceTitle:this.subscription==null},this.home));
if(l==4||l==6||l==5){this.askFindVisual(i,"U"+l)}if(l==100){this.enhanceU100Entry(i)}this.askAdjustEntries([i]);this.nextColumnId=[this.nextColumnId+1]%this.nbrColumns;this.entries.push(i)}catch(k){}};f.enhanceU100Entry=function(k){try{var m=this.home.getDocument().createEvent("Event");m.initEvent("googlePlusDecorateEvent",true,true);var j=this.home.getDocument().getElementById("box");
if(j!=null){j.dispatchEvent(m)}}catch(m){}var l=this;var i=this.element(k.getId()+"_entryBody");devhd.utils.HTMLUtils.cleanNode(i,{maxWidth:577,rtl:k.isContentRTL(),pinImage:this.feedly.getPreference("pinImage")});this.state="loaded"};f.markAllSubscriptionEntriesAsRead=function(i,k,j,l){this.state="batchMarkAsRead";this.reader.askMarkAllSubscriptionEntriesAsRead(i,k,j,l)
};f.onSubscriptionMarkedAsRead=function(i){if(this.feedId!=i){return}this.state="loaded"};f.onSubscriptionAdded=function(j,i,k){};f.onSubscriptionAddedToCategory=function(j,i,k){};f.onSubscriptionFullyAdded=function(i,k,j){if(this.feedId!=i){return}if(j==true){return}if(k!=null&&k.lenght>0){this.feedly.pushContext({uri:"category/"+k[0],pageNumber:0,title:devhd.utils.TermUtils.formatTitle(k[0]),level:1,category:k[0]})
}this.feedly.reloadPage({forceRecreate:true,disableAutoMarkAsRead:true})};f.onSubscriptionRemovedFromCategory=function(j,i){if(this.feedId!=j){return}var k=this;this.reader.askSubscription(j,function(n){k.subscription=n;var m="global.uncategorized";var l=k.subscription.listCategoryLabels();if(l.length>0){m=l[0]}this.feedly.pushContext({uri:"category/"+m,pageNumber:0,title:devhd.utils.TermUtils.formatTitle(m),level:1,category:m});
this.feedly.reloadPage({forceRecreate:true,disableAutoMarkAsRead:true})})};f.onSubscriptionRemoved=function(i){if(this.feedId!=i){return}this.feedly.reloadPage({forceRecreate:true,disableAutoMarkAsRead:true})};f.markPageAsRead=function(){this.signs.setMessage(d(91),100);var i=this;this.home.getDocument().defaultView.setTimeout(function(){var l=[];for(var k=0;
k<i.entries.length;k++){l.push(i.entries[k].getId())}i.reader.askMarkEntriesAsRead(l,function(){},function(j){i.signs.setMessage("Error:"+j)})},15)};f.findNextEntryId=function(n){var m=false;if(this.selectedEntryId==null){m=true}for(var k=0;k<this.entries.length;k++){if(m==true){if(n==true){var i=this.entries[k];var l=i.getId();if(i.isRead()==false){return l
}else{continue}}else{return this.entries[k].getId()}}if(this.entries[k].getId()==this.selectedEntryId){m=true}}return null};f.findPreviousEntryId=function(n){var m=false;if(this.selectedEntryId==null){m=true}for(var k=this.entries.length-1;k>=0;k--){if(m==true){if(n==true){var i=this.entries[k];var l=i.getId();if(i.isRead()==false){return l}else{continue
}}else{return this.entries[k].getId()}}if(this.entries[k].getId()==this.selectedEntryId){m=true}}};f.onPreviousEntry=function(k,i){var j=this.findPreviousEntryId(k);if(j!=null){if(i==true){if(this.getPreference("entryOverviewSize.desktop")!="100"){this.selectEntry(j,"toview")}}else{this.inlineEntry(j,true,true)}}else{this.feedly.loadPreviousPage({selectEntry:true,navigationMode:"keyboard"})
}};f.onNextEntry=function(k,i){var j=this.findNextEntryId(k);if(j==null){this.askMoreEntries()}else{if(i==true){if(this.getPreference("entryOverviewSize.desktop")!="100"){this.selectEntry(j,"toview")}}else{this.inlineEntry(j,true,true)}}if(this.nearingTheEnd()){this.askMoreEntries()}};f.nearingTheEnd=function(k){if(this.selectedEntryId==null||this.entries==null||this.entries.length==0){return true
}for(var j=0;j<this.entries.length;j++){if(this.entries[j].getId()==this.selectedEntryId){if(j>this.entries.length-5){return true}else{return false}}}return true};f.onEntryUntagged=function(j,i){this.updateTagHolders(j);if(this.pageInfo.uri=="tag/"+i){this.hideEntry(j)}}})();