"use strict";(function(){var d="pk_test_yoj2w7adyCRkmi35iS2f3TMK";var b="pk_live_atMEGqPDeLwMkj1NC8K1tZ32";var a=devhd.pkg("pages");a.ProPage=function(){};var c=a.ProPage.prototype=new a.BasePage();c.allowsSideArea=function(){return false};c.allowsPageHeader=function(){return false};c.service=function(f,e){this.pageInfo=f;this.width=e.width;this.feature=f.key;
this.initBase(e);if(this.home.isProPlan()){this.feedly.redirect("upgraded");return}this.feedly.closeMessageBar(true);this.startRenderHTML()};c.destroy=function(){this.destroyBase()};c.startRenderHTML=function(){try{var f=this.home.getDocument().createElement("script");f.type="text/javascript";f.src="https://checkout.stripe.com/v2/checkout.js";this.home.getDocument().getElementsByTagName("head")[0].appendChild(f)
}catch(i){this.signs.setMessage("failed to activate stripe:"+i.name+" -- "+i.message);return}if(this.feature!=null){this.analytics.trackPageview("sales/kickstarter/"+this.feature);this.analytics.trackEvent("sales.kickstarter",this.feature,this.home.getUserId()==null?"guest":"user")}var g=this.home.isStoreOpen()||this.feature=="abracadabra";this.feedly.setPageTitle("feedly Pro");
this.pageElem.innerHTML=templates.page.pro.layout(this.home.getUserId()!=null,this.home.isProPlan(),this.feature,g);if(this.feature=="checkout"){var h=this;this.home.getDocument().defaultView.setTimeout(function(){h.home.getDocument().defaultView.scroll(0,620);h.startCheckout()},250)}else{this.analytics.trackPageview("sales/kickstarter/datasheet");this.analytics.trackEvent("sales.kickstarter","datasheet",this.home.getUserId()==null?"guest":"user")
}};c.startCheckout=function(){var f=this;try{StripeCheckout.open({key:this.home.getDocument().defaultView.location.hostname.indexOf("cloud.feedly.com")>-1?b:d,address:false,amount:9900,currency:"usd",name:"Feedly Pro",description:"Lifetime edition",panelLabel:"Upgrade",token:function(e){f.handlePayment(e)},image:"https://s3.feedly.com/img/feedly-pro-payment-icon-128.png"});
this.analytics.trackPageview("sales/kickstarter/checkout");this.analytics.trackEvent("sales.kickstarter","checkout",this.home.getUserId()==null?"guest":"user")}catch(g){if(this.retrying==null){this.retrying=true;this.signs.setMessage("Loading stripe...");var f=this;this.home.getDocument().defaultView.setTimeout(function(){f.startCheckout()},2500)}}};
c.handlePayment=function(e){if(e.id!=null){this.analytics.trackPageview("sales/kickstarter/approved");this.analytics.trackEvent("sales.kickstarter","approved",this.home.getUserId()==null?"guest":"user");this.disableButtons();var f=this;$feedly("[feedly] starting upgrade: "+devhd.utils.JSONUtils.encode(e));this.home.service("io").post("!{cloud}/v3/payment?stripeToken="+encodeURIComponent(e.id)+"&userId="+f.home.getUserId()+"&ck="+new Date().getTime()+"&ct=feedly.desktop&cv="+feedlyApplicationVersion,"",function(g){try{f.analytics.trackPageview("sales/kickstarter/upgraded");
f.analytics.trackEvent("sales.kickstarter","upgraded",f.home.getUserId()==null?"guest":"user");f.disableButtons("Processing complete!");$feedly("[feedly] upgrade successful. "+g);var j=devhd.utils.JSONUtils.decode(g);var i=devhd.utils.SessionUtils.load();i.feedlyToken=j.accessToken;i.plan="pro";devhd.utils.SessionUtils.save(i);window.location.reload(true)
}catch(h){$feedly("Upgrade failed:"+h.name+" -- "+h.message);window.alert("Please reload feedly to access your new feedly Pro account");f.analytics.trackPageview("sales/kickstarter/error");f.analytics.trackEvent("sales.kickstarter","error",h.name)}},function(g,k){if(g==403){var i="Your card was declined.";try{var h=devhd.utils.JSONUtils.decode(k);if(h!=null&&h.errorMessage!=null){i=h.errorMessage
}}catch(j){$feedly("[pro] failed to extract error message:"+k)}f.disableButtons(i,"Please reload the page and retry.");f.analytics.trackPageview("sales/kickstarter/declined");f.analytics.trackEvent("sales.kickstarter","declined",403)}else{if(g==504){f.disableButtons("Processing timed out: "+g+" -- "+k,"Please try to log out and log back in.");f.analytics.trackPageview("sales/kickstarter/timeout");
f.analytics.trackEvent("sales.kickstarter","timeout",504)}else{f.disableButtons("Processing failed: "+g+" -- "+k,"Sorry! If you have questions, please email us at payment@feedly.com with the above error info.");f.analytics.trackPageview("sales/kickstarter/failed");f.analytics.trackEvent("sales.kickstarter","failed",g)}}},"application/json",{"$Authorization.feedly":"$FeedlyAuth","Content-Type":"application/json"})
}};c.disableButtons=function(h,g){var e=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"already"});for(var f=0;f<e.length;f++){e[f].innerHTML=h||"Processing payment. Please wait..."}e=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"button"});for(var f=0;f<e.length;f++){e[f].className="already";e[f].innerHTML=h||"Processing payment. Please wait..."
}if(g!=null){e=devhd.utils.HTMLUtils.findElements(this.pageElem,{className:"note"});for(var f=0;f<e.length;f++){e[f].innerHTML=g}}}})();